import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../environments/environment';
import { EventType, ProgramType, GroupDetailsModel, StateModel, DistrictModel, CreateSamitiModel, NearbyGroupsRequestBody } from '../models/home.model';
import { Observable } from 'rxjs';
import { signal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class HomeService {

  private baseUrl = environment.apiBaseUrl;

  constructor(private http: HttpClient) {}

  states: StateModel[] = [
    { id: 1,  name: 'Jammu and Kashmir',                             abbreviation: 'INJK', stateId: 1  },
    { id: 2,  name: 'Himachal Pradesh',                              abbreviation: 'INHP', stateId: 2  },
    { id: 3,  name: 'Punjab',                                        abbreviation: 'INPB', stateId: 3  },
    { id: 4,  name: 'Chandigarh',                                    abbreviation: 'INCH', stateId: 4  },
    { id: 5,  name: 'Uttaranchal',                                   abbreviation: 'INUT', stateId: 5  },
    { id: 6,  name: 'Haryana',                                       abbreviation: 'INHR', stateId: 6  },
    { id: 7,  name: 'Delhi',                                         abbreviation: 'INDL', stateId: 7  },
    { id: 8,  name: 'Rajasthan',                                     abbreviation: 'INRJ', stateId: 8  },
    { id: 9,  name: 'Uttar Pradesh',                                 abbreviation: 'INUP', stateId: 9  },
    { id: 10, name: 'Bihar',                                         abbreviation: 'INBR', stateId: 10 },
    { id: 11, name: 'Sikkim',                                        abbreviation: 'INSK', stateId: 11 },
    { id: 12, name: 'Arunachal Pradesh',                             abbreviation: 'INAR', stateId: 12 },
    { id: 13, name: 'Nagaland',                                      abbreviation: 'INNL', stateId: 13 },
    { id: 14, name: 'Manipur',                                       abbreviation: 'INMN', stateId: 14 },
    { id: 15, name: 'Mizoram',                                       abbreviation: 'INMZ', stateId: 15 },
    { id: 16, name: 'Tripura',                                       abbreviation: 'INTR', stateId: 16 },
    { id: 17, name: 'Meghalaya',                                     abbreviation: 'INML', stateId: 17 },
    { id: 18, name: 'Assam',                                         abbreviation: 'INAS', stateId: 18 },
    { id: 19, name: 'West Bengal',                                   abbreviation: 'INWB', stateId: 19 },
    { id: 20, name: 'Jharkhand',                                     abbreviation: 'INJH', stateId: 20 },
    { id: 21, name: 'Orissa',                                        abbreviation: 'INOR', stateId: 21 },
    { id: 22, name: 'Chhattisgarh',                                  abbreviation: 'INCT', stateId: 22 },
    { id: 23, name: 'Madhya Pradesh',                                abbreviation: 'INMP', stateId: 23 },
    { id: 24, name: 'Gujarat',                                       abbreviation: 'INGJ', stateId: 24 },
    { id: 25, name: 'Dādra and Nagar Haveli and Damān and Diu',      abbreviation: 'INDH', stateId: 26 },
    { id: 26, name: 'Maharashtra',                                   abbreviation: 'INMH', stateId: 27 },
    { id: 27, name: 'Karnataka',                                     abbreviation: 'INKA', stateId: 29 },
    { id: 28, name: 'Goa',                                           abbreviation: 'INGA', stateId: 30 },
    { id: 29, name: 'Lakshadweep',                                   abbreviation: 'INLD', stateId: 31 },
    { id: 30, name: 'Kerala',                                        abbreviation: 'INKL', stateId: 32 },
    { id: 31, name: 'Tamil Nadu',                                    abbreviation: 'INTN', stateId: 33 },
    { id: 32, name: 'Puducherry',                                    abbreviation: 'INPY', stateId: 34 },
    { id: 33, name: 'Andaman and Nicobar',                           abbreviation: 'INAN', stateId: 35 },
    { id: 34, name: 'Telangana',                                     abbreviation: 'INTG', stateId: 36 },
    { id: 35, name: 'Andhra Pradesh',                                abbreviation: 'INAP', stateId: 37 },
    { id: 36, name: 'Ladakh',                                        abbreviation: 'INLA', stateId: 38 },
  ];

  districts: { [stateId: number]: DistrictModel[] } = {
    1: [
      { id: 1,  name: 'Anantnag'       },
      { id: 2,  name: 'Bandipora'      },
      { id: 3,  name: 'Baramulla'      },
      { id: 4,  name: 'Budgam'         },
      { id: 5,  name: 'Doda'           },
      { id: 6,  name: 'Ganderbal'      },
      { id: 7,  name: 'Jammu'          },
      { id: 8,  name: 'Kathua'         },
      { id: 9,  name: 'Kishtwar'       },
      { id: 10, name: 'Kulgam'         },
      { id: 11, name: 'Kupwara'        },
      { id: 12, name: 'Poonch'         },
      { id: 13, name: 'Pulwama'        },
      { id: 14, name: 'Rajouri'        },
      { id: 15, name: 'Ramban'         },
      { id: 16, name: 'Reasi'          },
      { id: 17, name: 'Samba'          },
      { id: 18, name: 'Shopian'        },
      { id: 19, name: 'Srinagar'       },
      { id: 20, name: 'Udhampur'       },
    ],
    2: [
      { id: 1,  name: 'Bilaspur'         },
      { id: 2,  name: 'Chamba'           },
      { id: 3,  name: 'Hamirpur'         },
      { id: 4,  name: 'Kangra'           },
      { id: 5,  name: 'Kinnaur'          },
      { id: 6,  name: 'Kullu'            },
      { id: 7,  name: 'Lahaul and Spiti' },
      { id: 8,  name: 'Mandi'            },
      { id: 9,  name: 'Shimla'           },
      { id: 10, name: 'Sirmaur'          },
      { id: 11, name: 'Solan'            },
      { id: 12, name: 'Una'              },
    ],
    3: [
      { id: 1,  name: 'Amritsar'        },
      { id: 2,  name: 'Barnala'         },
      { id: 3,  name: 'Bathinda'        },
      { id: 4,  name: 'Faridkot'        },
      { id: 5,  name: 'Fatehgarh Sahib' },
      { id: 6,  name: 'Fazilka'         },
      { id: 7,  name: 'Ferozepur'       },
      { id: 8,  name: 'Gurdaspur'       },
      { id: 9,  name: 'Hoshiarpur'      },
      { id: 10, name: 'Jalandhar'       },
      { id: 11, name: 'Kapurthala'      },
      { id: 12, name: 'Ludhiana'        },
      { id: 13, name: 'Mansa'           },
      { id: 14, name: 'Moga'            },
      { id: 15, name: 'Mohali'          },
      { id: 16, name: 'Muktsar'         },
      { id: 17, name: 'Nawan Shahr'     },
      { id: 18, name: 'Pathankot'       },
      { id: 19, name: 'Patiala'         },
      { id: 20, name: 'Ropar'           },
      { id: 21, name: 'Sangrur'         },
      { id: 22, name: 'Tarn Taran'      },
    ],
    4: [
      { id: 1, name: 'Chandigarh' },
    ],
    5: [
      { id: 1,  name: 'Almora'           },
      { id: 2,  name: 'Bageshwar'        },
      { id: 3,  name: 'Chamoli'          },
      { id: 4,  name: 'Champawat'        },
      { id: 5,  name: 'Dehradun'         },
      { id: 6,  name: 'Haridwar'         },
      { id: 7,  name: 'Nainital'         },
      { id: 8,  name: 'Pauri Garhwal'    },
      { id: 9,  name: 'Pithoragarh'      },
      { id: 10, name: 'Rudraprayag'      },
      { id: 11, name: 'Tehri Garhwal'    },
      { id: 12, name: 'Udham Singh Nagar'},
      { id: 13, name: 'Uttarkashi'       },
    ],
    6: [
      { id: 1,  name: 'Ambala'         },
      { id: 2,  name: 'Bhiwani'        },
      { id: 3,  name: 'Charkhi Dadri'  },
      { id: 4,  name: 'Faridabad'      },
      { id: 5,  name: 'Fatehabad'      },
      { id: 6,  name: 'Gurugram'       },
      { id: 7,  name: 'Hisar'          },
      { id: 8,  name: 'Jhajjar'        },
      { id: 9,  name: 'Jind'           },
      { id: 10, name: 'Kaithal'        },
      { id: 11, name: 'Karnal'         },
      { id: 12, name: 'Kurukshetra'    },
      { id: 13, name: 'Mahendragarh'   },
      { id: 14, name: 'Nuh'            },
      { id: 15, name: 'Palwal'         },
      { id: 16, name: 'Panchkula'      },
      { id: 17, name: 'Panipat'        },
      { id: 18, name: 'Rewari'         },
      { id: 19, name: 'Rohtak'         },
      { id: 20, name: 'Sirsa'          },
      { id: 21, name: 'Sonipat'        },
      { id: 22, name: 'Yamunanagar'    },
    ],
    7: [
      { id: 1,  name: 'Central Delhi'    },
      { id: 2,  name: 'East Delhi'       },
      { id: 3,  name: 'New Delhi'        },
      { id: 4,  name: 'North Delhi'      },
      { id: 5,  name: 'North East Delhi' },
      { id: 6,  name: 'North West Delhi' },
      { id: 7,  name: 'Shahdara'         },
      { id: 8,  name: 'South Delhi'      },
      { id: 9,  name: 'South East Delhi' },
      { id: 10, name: 'South West Delhi' },
      { id: 11, name: 'West Delhi'       },
    ],
    8: [
      { id: 1,  name: 'Ajmer'           },
      { id: 2,  name: 'Alwar'           },
      { id: 3,  name: 'Banswara'        },
      { id: 4,  name: 'Baran'           },
      { id: 5,  name: 'Barmer'          },
      { id: 6,  name: 'Bharatpur'       },
      { id: 7,  name: 'Bhilwara'        },
      { id: 8,  name: 'Bikaner'         },
      { id: 9,  name: 'Bundi'           },
      { id: 10, name: 'Chittorgarh'     },
      { id: 11, name: 'Churu'           },
      { id: 12, name: 'Dausa'           },
      { id: 13, name: 'Dholpur'         },
      { id: 14, name: 'Dungarpur'       },
      { id: 15, name: 'Hanumangarh'     },
      { id: 16, name: 'Jaipur'          },
      { id: 17, name: 'Jaisalmer'       },
      { id: 18, name: 'Jalore'          },
      { id: 19, name: 'Jhalawar'        },
      { id: 20, name: 'Jhunjhunu'       },
      { id: 21, name: 'Jodhpur'         },
      { id: 22, name: 'Karauli'         },
      { id: 23, name: 'Kota'            },
      { id: 24, name: 'Nagaur'          },
      { id: 25, name: 'Pali'            },
      { id: 26, name: 'Pratapgarh'      },
      { id: 27, name: 'Rajsamand'       },
      { id: 28, name: 'Sawai Madhopur'  },
      { id: 29, name: 'Sikar'           },
      { id: 30, name: 'Sirohi'          },
      { id: 31, name: 'Sri Ganganagar'  },
      { id: 32, name: 'Tonk'            },
      { id: 33, name: 'Udaipur'         },
    ],
    9: [
      { id: 1,  name: 'Agra'                  },
      { id: 2,  name: 'Aligarh'               },
      { id: 3,  name: 'Prayagraj'             },
      { id: 4,  name: 'Ambedkar Nagar'        },
      { id: 5,  name: 'Amethi'                },
      { id: 6,  name: 'Amroha'                },
      { id: 7,  name: 'Auraiya'               },
      { id: 8,  name: 'Azamgarh'              },
      { id: 9,  name: 'Baghpat'               },
      { id: 10, name: 'Bahraich'              },
      { id: 11, name: 'Ballia'                },
      { id: 12, name: 'Balrampur'             },
      { id: 13, name: 'Banda'                 },
      { id: 14, name: 'Barabanki'             },
      { id: 15, name: 'Bareilly'              },
      { id: 16, name: 'Basti'                 },
      { id: 17, name: 'Bhadohi'               },
      { id: 18, name: 'Bijnor'                },
      { id: 19, name: 'Budaun'                },
      { id: 20, name: 'Bulandshahr'           },
      { id: 21, name: 'Chandauli'             },
      { id: 22, name: 'Chitrakoot'            },
      { id: 23, name: 'Deoria'                },
      { id: 24, name: 'Etah'                  },
      { id: 25, name: 'Etawah'                },
      { id: 26, name: 'Ayodhya'               },
      { id: 27, name: 'Farrukhabad'           },
      { id: 28, name: 'Fatehpur'              },
      { id: 29, name: 'Firozabad'             },
      { id: 30, name: 'Gautam Buddha Nagar'   },
      { id: 31, name: 'Ghaziabad'             },
      { id: 32, name: 'Ghazipur'              },
      { id: 33, name: 'Gonda'                 },
      { id: 34, name: 'Gorakhpur'             },
      { id: 35, name: 'Hamirpur'              },
      { id: 36, name: 'Hapur'                 },
      { id: 37, name: 'Hardoi'                },
      { id: 38, name: 'Hathras'               },
      { id: 39, name: 'Jalaun'                },
      { id: 40, name: 'Jaunpur'               },
      { id: 41, name: 'Jhansi'                },
      { id: 42, name: 'Kannauj'               },
      { id: 43, name: 'Kanpur Dehat'          },
      { id: 44, name: 'Kanpur Nagar'          },
      { id: 45, name: 'Kasganj'               },
      { id: 46, name: 'Kaushambi'             },
      { id: 47, name: 'Kushinagar'            },
      { id: 48, name: 'Lakhimpur Kheri'       },
      { id: 49, name: 'Lalitpur'              },
      { id: 50, name: 'Lucknow'               },
      { id: 51, name: 'Maharajganj'           },
      { id: 52, name: 'Mahoba'                },
      { id: 53, name: 'Mainpuri'              },
      { id: 54, name: 'Mathura'               },
      { id: 55, name: 'Mau'                   },
      { id: 56, name: 'Meerut'                },
      { id: 57, name: 'Mirzapur'              },
      { id: 58, name: 'Moradabad'             },
      { id: 59, name: 'Muzaffarnagar'         },
      { id: 60, name: 'Pilibhit'              },
      { id: 61, name: 'Pratapgarh'            },
      { id: 62, name: 'Rae Bareli'            },
      { id: 63, name: 'Rampur'                },
      { id: 64, name: 'Saharanpur'            },
      { id: 65, name: 'Sambhal'               },
      { id: 66, name: 'Sant Kabir Nagar'      },
      { id: 67, name: 'Shahjahanpur'          },
      { id: 68, name: 'Shamli'                },
      { id: 69, name: 'Shravasti'             },
      { id: 70, name: 'Siddharthnagar'        },
      { id: 71, name: 'Sitapur'               },
      { id: 72, name: 'Sonbhadra'             },
      { id: 73, name: 'Sultanpur'             },
      { id: 74, name: 'Unnao'                 },
      { id: 75, name: 'Varanasi'              },
    ],
    10: [
      { id: 1,  name: 'Araria'          },
      { id: 2,  name: 'Arwal'           },
      { id: 3,  name: 'Aurangabad'      },
      { id: 4,  name: 'Banka'           },
      { id: 5,  name: 'Begusarai'       },
      { id: 6,  name: 'Bhagalpur'       },
      { id: 7,  name: 'Bhojpur'         },
      { id: 8,  name: 'Buxar'           },
      { id: 9,  name: 'Darbhanga'       },
      { id: 10, name: 'East Champaran'  },
      { id: 11, name: 'Gaya'            },
      { id: 12, name: 'Gopalganj'       },
      { id: 13, name: 'Jamui'           },
      { id: 14, name: 'Jehanabad'       },
      { id: 15, name: 'Kaimur'          },
      { id: 16, name: 'Katihar'         },
      { id: 17, name: 'Khagaria'        },
      { id: 18, name: 'Kishanganj'      },
      { id: 19, name: 'Lakhisarai'      },
      { id: 20, name: 'Madhepura'       },
      { id: 21, name: 'Madhubani'       },
      { id: 22, name: 'Munger'          },
      { id: 23, name: 'Muzaffarpur'     },
      { id: 24, name: 'Nalanda'         },
      { id: 25, name: 'Nawada'          },
      { id: 26, name: 'Patna'           },
      { id: 27, name: 'Purnia'          },
      { id: 28, name: 'Rohtas'          },
      { id: 29, name: 'Saharsa'         },
      { id: 30, name: 'Samastipur'      },
      { id: 31, name: 'Saran'           },
      { id: 32, name: 'Sheikhpura'      },
      { id: 33, name: 'Sheohar'         },
      { id: 34, name: 'Sitamarhi'       },
      { id: 35, name: 'Siwan'           },
      { id: 36, name: 'Supaul'          },
      { id: 37, name: 'Vaishali'        },
      { id: 38, name: 'West Champaran'  },
    ],
    11: [
      { id: 1, name: 'East Sikkim'  },
      { id: 2, name: 'North Sikkim' },
      { id: 3, name: 'South Sikkim' },
      { id: 4, name: 'West Sikkim'  },
    ],
    12: [
      { id: 1,  name: 'Anjaw'                },
      { id: 2,  name: 'Changlang'            },
      { id: 3,  name: 'Dibang Valley'        },
      { id: 4,  name: 'East Kameng'          },
      { id: 5,  name: 'East Siang'           },
      { id: 6,  name: 'Kamle'                },
      { id: 7,  name: 'Kra Daadi'            },
      { id: 8,  name: 'Kurung Kumey'         },
      { id: 9,  name: 'Lepa Rada'            },
      { id: 10, name: 'Lohit'                },
      { id: 11, name: 'Longding'             },
      { id: 12, name: 'Lower Dibang Valley'  },
      { id: 13, name: 'Lower Siang'          },
      { id: 14, name: 'Lower Subansiri'      },
      { id: 15, name: 'Namsai'               },
      { id: 16, name: 'Pakke-Kessang'        },
      { id: 17, name: 'Papum Pare'           },
      { id: 18, name: 'Shi Yomi'             },
      { id: 19, name: 'Siang'                },
      { id: 20, name: 'Tawang'               },
      { id: 21, name: 'Tirap'                },
      { id: 22, name: 'Upper Siang'          },
      { id: 23, name: 'Upper Subansiri'      },
      { id: 24, name: 'West Kameng'          },
      { id: 25, name: 'West Siang'           },
    ],
    13: [
      { id: 1,  name: 'Chumoukedima' },
      { id: 2,  name: 'Dimapur'      },
      { id: 3,  name: 'Kiphire'      },
      { id: 4,  name: 'Kohima'       },
      { id: 5,  name: 'Longleng'     },
      { id: 6,  name: 'Mokokchung'   },
      { id: 7,  name: 'Mon'          },
      { id: 8,  name: 'Niuland'      },
      { id: 9,  name: 'Noklak'       },
      { id: 10, name: 'Peren'        },
      { id: 11, name: 'Phek'         },
      { id: 12, name: 'Shamator'     },
      { id: 13, name: 'Tseminyü'     },
      { id: 14, name: 'Tuensang'     },
      { id: 15, name: 'Wokha'        },
      { id: 16, name: 'Zunheboto'    },
    ],
    14: [
      { id: 1,  name: 'Bishnupur'    },
      { id: 2,  name: 'Chandel'      },
      { id: 3,  name: 'Churachandpur'},
      { id: 4,  name: 'Imphal East'  },
      { id: 5,  name: 'Imphal West'  },
      { id: 6,  name: 'Jiribam'      },
      { id: 7,  name: 'Kakching'     },
      { id: 8,  name: 'Kamjong'      },
      { id: 9,  name: 'Kangpokpi'    },
      { id: 10, name: 'Noney'        },
      { id: 11, name: 'Pherzawl'     },
      { id: 12, name: 'Senapati'     },
      { id: 13, name: 'Tamenglong'   },
      { id: 14, name: 'Tengnoupal'   },
      { id: 15, name: 'Thoubal'      },
      { id: 16, name: 'Ukhrul'       },
    ],
    15: [
      { id: 1,  name: 'Aizawl'     },
      { id: 2,  name: 'Champhai'   },
      { id: 3,  name: 'Hnahthial'  },
      { id: 4,  name: 'Khawzawl'   },
      { id: 5,  name: 'Kolasib'    },
      { id: 6,  name: 'Lawngtlai'  },
      { id: 7,  name: 'Lunglei'    },
      { id: 8,  name: 'Mamit'      },
      { id: 9,  name: 'Saitual'    },
      { id: 10, name: 'Serchhip'   },
    ],
    16: [
      { id: 1, name: 'Dhalai'        },
      { id: 2, name: 'Gomati'        },
      { id: 3, name: 'Khowai'        },
      { id: 4, name: 'North Tripura' },
      { id: 5, name: 'Sepahijala'    },
      { id: 6, name: 'South Tripura' },
      { id: 7, name: 'Unakoti'       },
      { id: 8, name: 'West Tripura'  },
    ],
    17: [
      { id: 1,  name: 'East Garo Hills'          },
      { id: 2,  name: 'East Jaintia Hills'        },
      { id: 3,  name: 'East Khasi Hills'          },
      { id: 4,  name: 'Eastern West Khasi Hills'  },
      { id: 5,  name: 'North Garo Hills'          },
      { id: 6,  name: 'Ri Bhoi'                   },
      { id: 7,  name: 'South Garo Hills'          },
      { id: 8,  name: 'South West Garo Hills'     },
      { id: 9,  name: 'South West Khasi Hills'    },
      { id: 10, name: 'West Garo Hills'           },
      { id: 11, name: 'West Jaintia Hills'        },
      { id: 12, name: 'West Khasi Hills'          },
    ],
    18: [
      { id: 1,  name: 'Bajali'                    },
      { id: 2,  name: 'Baksa'                     },
      { id: 3,  name: 'Barpeta'                   },
      { id: 4,  name: 'Biswanath'                 },
      { id: 5,  name: 'Bongaigaon'                },
      { id: 6,  name: 'Cachar'                    },
      { id: 7,  name: 'Charaideo'                 },
      { id: 8,  name: 'Chirang'                   },
      { id: 9,  name: 'Darrang'                   },
      { id: 10, name: 'Dhemaji'                   },
      { id: 11, name: 'Dhubri'                    },
      { id: 12, name: 'Dibrugarh'                 },
      { id: 13, name: 'Dima Hasao'                },
      { id: 14, name: 'Goalpara'                  },
      { id: 15, name: 'Golaghat'                  },
      { id: 16, name: 'Hailakandi'                },
      { id: 17, name: 'Hojai'                     },
      { id: 18, name: 'Jorhat'                    },
      { id: 19, name: 'Kamrup'                    },
      { id: 20, name: 'Kamrup Metropolitan'       },
      { id: 21, name: 'Karbi Anglong'             },
      { id: 22, name: 'Karimganj'                 },
      { id: 23, name: 'Kokrajhar'                 },
      { id: 24, name: 'Lakhimpur'                 },
      { id: 25, name: 'Majuli'                    },
      { id: 26, name: 'Morigaon'                  },
      { id: 27, name: 'Nagaon'                    },
      { id: 28, name: 'Nalbari'                   },
      { id: 29, name: 'Sivasagar'                 },
      { id: 30, name: 'Sonitpur'                  },
      { id: 31, name: 'South Salmara-Mankachar'   },
      { id: 32, name: 'Tinsukia'                  },
      { id: 33, name: 'Udalguri'                  },
      { id: 34, name: 'West Karbi Anglong'        },
    ],
    19: [
      { id: 1,  name: 'Alipurduar'          },
      { id: 2,  name: 'Bankura'             },
      { id: 3,  name: 'Birbhum'             },
      { id: 4,  name: 'Cooch Behar'         },
      { id: 5,  name: 'Dakshin Dinajpur'    },
      { id: 6,  name: 'Darjeeling'          },
      { id: 7,  name: 'Hooghly'             },
      { id: 8,  name: 'Howrah'              },
      { id: 9,  name: 'Jalpaiguri'          },
      { id: 10, name: 'Jhargram'            },
      { id: 11, name: 'Kalimpong'           },
      { id: 12, name: 'Kolkata'             },
      { id: 13, name: 'Malda'               },
      { id: 14, name: 'Murshidabad'         },
      { id: 15, name: 'Nadia'               },
      { id: 16, name: 'North 24 Parganas'   },
      { id: 17, name: 'Paschim Bardhaman'   },
      { id: 18, name: 'Paschim Medinipur'   },
      { id: 19, name: 'Purba Bardhaman'     },
      { id: 20, name: 'Purba Medinipur'     },
      { id: 21, name: 'Purulia'             },
      { id: 22, name: 'South 24 Parganas'   },
      { id: 23, name: 'Uttar Dinajpur'      },
    ],
    20: [
      { id: 1,  name: 'Bokaro'                  },
      { id: 2,  name: 'Chatra'                  },
      { id: 3,  name: 'Deoghar'                 },
      { id: 4,  name: 'Dhanbad'                 },
      { id: 5,  name: 'Dumka'                   },
      { id: 6,  name: 'East Singhbhum'          },
      { id: 7,  name: 'Garhwa'                  },
      { id: 8,  name: 'Giridih'                 },
      { id: 9,  name: 'Godda'                   },
      { id: 10, name: 'Gumla'                   },
      { id: 11, name: 'Hazaribagh'              },
      { id: 12, name: 'Jamtara'                 },
      { id: 13, name: 'Khunti'                  },
      { id: 14, name: 'Koderma'                 },
      { id: 15, name: 'Latehar'                 },
      { id: 16, name: 'Lohardaga'               },
      { id: 17, name: 'Pakur'                   },
      { id: 18, name: 'Palamu'                  },
      { id: 19, name: 'Ramgarh'                 },
      { id: 20, name: 'Ranchi'                  },
      { id: 21, name: 'Sahebganj'               },
      { id: 22, name: 'Seraikela Kharsawan'     },
      { id: 23, name: 'Simdega'                 },
      { id: 24, name: 'West Singhbhum'          },
    ],
    21: [
      { id: 1,  name: 'Angul'          },
      { id: 2,  name: 'Balangir'       },
      { id: 3,  name: 'Balasore'       },
      { id: 4,  name: 'Bargarh'        },
      { id: 5,  name: 'Bhadrak'        },
      { id: 6,  name: 'Boudh'          },
      { id: 7,  name: 'Cuttack'        },
      { id: 8,  name: 'Deogarh'        },
      { id: 9,  name: 'Dhenkanal'      },
      { id: 10, name: 'Gajapati'       },
      { id: 11, name: 'Ganjam'         },
      { id: 12, name: 'Jagatsinghpur'  },
      { id: 13, name: 'Jajpur'         },
      { id: 14, name: 'Jharsuguda'     },
      { id: 15, name: 'Kalahandi'      },
      { id: 16, name: 'Kandhamal'      },
      { id: 17, name: 'Kendrapara'     },
      { id: 18, name: 'Kendujhar'      },
      { id: 19, name: 'Khordha'        },
      { id: 20, name: 'Koraput'        },
      { id: 21, name: 'Malkangiri'     },
      { id: 22, name: 'Mayurbhanj'     },
      { id: 23, name: 'Nabarangpur'    },
      { id: 24, name: 'Nayagarh'       },
      { id: 25, name: 'Nuapada'        },
      { id: 26, name: 'Puri'           },
      { id: 27, name: 'Rayagada'       },
      { id: 28, name: 'Sambalpur'      },
      { id: 29, name: 'Subarnapur'     },
      { id: 30, name: 'Sundergarh'     },
    ],
    22: [
      { id: 1,  name: 'Balod'         },
      { id: 2,  name: 'Baloda Bazar'  },
      { id: 3,  name: 'Balrampur'     },
      { id: 4,  name: 'Bametara'      },
      { id: 5,  name: 'Bijapur'       },
      { id: 6,  name: 'Bilaspur'      },
      { id: 7,  name: 'Dantewada'     },
      { id: 8,  name: 'Dhamtari'      },
      { id: 9,  name: 'Durg'          },
      { id: 10, name: 'Gariaband'     },
      { id: 11, name: 'Janjgir-Champa'},
      { id: 12, name: 'Jashpur'       },
      { id: 13, name: 'Kanker'        },
      { id: 14, name: 'Kawardha'      },
      { id: 15, name: 'Korba'         },
      { id: 16, name: 'Koriya'        },
      { id: 17, name: 'Mahasamund'    },
      { id: 18, name: 'Mungeli'       },
      { id: 19, name: 'Narayanpur'    },
      { id: 20, name: 'Raigarh'       },
      { id: 21, name: 'Raipur'        },
      { id: 22, name: 'Rajnandgaon'   },
      { id: 23, name: 'Sukma'         },
      { id: 24, name: 'Surajpur'      },
      { id: 25, name: 'Surguja'       },
    ],
    23: [
      { id: 1,  name: 'Agar Malwa'    },
      { id: 2,  name: 'Alirajpur'     },
      { id: 3,  name: 'Anuppur'       },
      { id: 4,  name: 'Ashoknagar'    },
      { id: 5,  name: 'Balaghat'      },
      { id: 6,  name: 'Barwani'       },
      { id: 7,  name: 'Betul'         },
      { id: 8,  name: 'Bhind'         },
      { id: 9,  name: 'Bhopal'        },
      { id: 10, name: 'Burhanpur'     },
      { id: 11, name: 'Chhatarpur'    },
      { id: 12, name: 'Chhindwara'    },
      { id: 13, name: 'Damoh'         },
      { id: 14, name: 'Datia'         },
      { id: 15, name: 'Dewas'         },
      { id: 16, name: 'Dhar'          },
      { id: 17, name: 'Dindori'       },
      { id: 18, name: 'Guna'          },
      { id: 19, name: 'Gwalior'       },
      { id: 20, name: 'Harda'         },
      { id: 21, name: 'Narmadapuram'  },
      { id: 22, name: 'Indore'        },
      { id: 23, name: 'Jabalpur'      },
      { id: 24, name: 'Jhabua'        },
      { id: 25, name: 'Katni'         },
      { id: 26, name: 'Khandwa'       },
      { id: 27, name: 'Khargone'      },
      { id: 28, name: 'Mandla'        },
      { id: 29, name: 'Mandsaur'      },
      { id: 30, name: 'Morena'        },
      { id: 31, name: 'Narsinghpur'   },
      { id: 32, name: 'Neemuch'       },
      { id: 33, name: 'Niwari'        },
      { id: 34, name: 'Panna'         },
      { id: 35, name: 'Raisen'        },
      { id: 36, name: 'Rajgarh'       },
      { id: 37, name: 'Ratlam'        },
      { id: 38, name: 'Rewa'          },
      { id: 39, name: 'Sagar'         },
      { id: 40, name: 'Satna'         },
      { id: 41, name: 'Sehore'        },
      { id: 42, name: 'Seoni'         },
      { id: 43, name: 'Shahdol'       },
      { id: 44, name: 'Shajapur'      },
      { id: 45, name: 'Sheopur'       },
      { id: 46, name: 'Shivpuri'      },
      { id: 47, name: 'Sidhi'         },
      { id: 48, name: 'Singrauli'     },
      { id: 49, name: 'Tikamgarh'     },
      { id: 50, name: 'Ujjain'        },
      { id: 51, name: 'Umaria'        },
      { id: 52, name: 'Vidisha'       },
    ],
    24: [
      { id: 1,  name: 'Ahmedabad'          },
      { id: 2,  name: 'Amreli'             },
      { id: 3,  name: 'Anand'              },
      { id: 4,  name: 'Aravalli'           },
      { id: 5,  name: 'Banaskantha'        },
      { id: 6,  name: 'Bharuch'            },
      { id: 7,  name: 'Bhavnagar'          },
      { id: 8,  name: 'Botad'              },
      { id: 9,  name: 'Chhota Udaipur'     },
      { id: 10, name: 'Dahod'              },
      { id: 11, name: 'Dang'               },
      { id: 12, name: 'Devbhoomi Dwarka'   },
      { id: 13, name: 'Gandhinagar'        },
      { id: 14, name: 'Gir Somnath'        },
      { id: 15, name: 'Jamnagar'           },
      { id: 16, name: 'Junagadh'           },
      { id: 17, name: 'Kheda'              },
      { id: 18, name: 'Kutch'              },
      { id: 19, name: 'Mahisagar'          },
      { id: 20, name: 'Mehsana'            },
      { id: 21, name: 'Morbi'              },
      { id: 22, name: 'Narmada'            },
      { id: 23, name: 'Navsari'            },
      { id: 24, name: 'Panchmahal'         },
      { id: 25, name: 'Patan'              },
      { id: 26, name: 'Porbandar'          },
      { id: 27, name: 'Rajkot'             },
      { id: 28, name: 'Sabarkantha'        },
      { id: 29, name: 'Surat'              },
      { id: 30, name: 'Surendranagar'      },
      { id: 31, name: 'Tapi'               },
      { id: 32, name: 'Vadodara'           },
      { id: 33, name: 'Valsad'             },
    ],
    25: [
      { id: 1, name: 'Dadra and Nagar Haveli' },
      { id: 2, name: 'Daman'                  },
      { id: 3, name: 'Diu'                    },
    ],
    26: [
      { id: 1,  name: 'Ahmednagar'      },
      { id: 2,  name: 'Akola'           },
      { id: 3,  name: 'Amravati'        },
      { id: 4,  name: 'Aurangabad'      },
      { id: 5,  name: 'Beed'            },
      { id: 6,  name: 'Bhandara'        },
      { id: 7,  name: 'Buldhana'        },
      { id: 8,  name: 'Chandrapur'      },
      { id: 9,  name: 'Dhule'           },
      { id: 10, name: 'Gadchiroli'      },
      { id: 11, name: 'Gondia'          },
      { id: 12, name: 'Hingoli'         },
      { id: 13, name: 'Jalgaon'         },
      { id: 14, name: 'Jalna'           },
      { id: 15, name: 'Kolhapur'        },
      { id: 16, name: 'Latur'           },
      { id: 17, name: 'Mumbai City'     },
      { id: 18, name: 'Mumbai Suburban' },
      { id: 19, name: 'Nagpur'          },
      { id: 20, name: 'Nanded'          },
      { id: 21, name: 'Nandurbar'       },
      { id: 22, name: 'Nashik'          },
      { id: 23, name: 'Osmanabad'       },
      { id: 24, name: 'Palghar'         },
      { id: 25, name: 'Parbhani'        },
      { id: 26, name: 'Pune'            },
      { id: 27, name: 'Raigad'          },
      { id: 28, name: 'Ratnagiri'       },
      { id: 29, name: 'Sangli'          },
      { id: 30, name: 'Satara'          },
      { id: 31, name: 'Sindhudurg'      },
      { id: 32, name: 'Solapur'         },
      { id: 33, name: 'Thane'           },
      { id: 34, name: 'Wardha'          },
      { id: 35, name: 'Washim'          },
      { id: 36, name: 'Yavatmal'        },
    ],
    27: [
      { id: 1,  name: 'Bagalkot'         },
      { id: 2,  name: 'Ballari'          },
      { id: 3,  name: 'Belagavi'         },
      { id: 4,  name: 'Bengaluru Rural'  },
      { id: 5,  name: 'Bengaluru Urban'  },
      { id: 6,  name: 'Bidar'            },
      { id: 7,  name: 'Chamarajanagar'   },
      { id: 8,  name: 'Chikkaballapur'   },
      { id: 9,  name: 'Chikkamagaluru'   },
      { id: 10, name: 'Chitradurga'      },
      { id: 11, name: 'Dakshina Kannada' },
      { id: 12, name: 'Davanagere'       },
      { id: 13, name: 'Dharwad'          },
      { id: 14, name: 'Gadag'            },
      { id: 15, name: 'Hassan'           },
      { id: 16, name: 'Haveri'           },
      { id: 17, name: 'Kalaburagi'       },
      { id: 18, name: 'Kodagu'           },
      { id: 19, name: 'Kolar'            },
      { id: 20, name: 'Koppal'           },
      { id: 21, name: 'Mandya'           },
      { id: 22, name: 'Mysuru'           },
      { id: 23, name: 'Raichur'          },
      { id: 24, name: 'Ramanagara'       },
      { id: 25, name: 'Shivamogga'       },
      { id: 26, name: 'Tumakuru'         },
      { id: 27, name: 'Udupi'            },
      { id: 28, name: 'Uttara Kannada'   },
      { id: 29, name: 'Vijayapura'       },
      { id: 30, name: 'Yadgir'           },
    ],
    28: [
      { id: 1, name: 'North Goa' },
      { id: 2, name: 'South Goa' },
    ],
    29: [
      { id: 1,  name: 'Agatti'    },
      { id: 2,  name: 'Amini'     },
      { id: 3,  name: 'Andrott'   },
      { id: 4,  name: 'Bitra'     },
      { id: 5,  name: 'Chetlat'   },
      { id: 6,  name: 'Kadmat'    },
      { id: 7,  name: 'Kalpeni'   },
      { id: 8,  name: 'Kavaratti' },
      { id: 9,  name: 'Kiltan'    },
      { id: 10, name: 'Minicoy'   },
    ],
    30: [
      { id: 1,  name: 'Alappuzha'        },
      { id: 2,  name: 'Ernakulam'        },
      { id: 3,  name: 'Idukki'           },
      { id: 4,  name: 'Kannur'           },
      { id: 5,  name: 'Kasaragod'        },
      { id: 6,  name: 'Kollam'           },
      { id: 7,  name: 'Kottayam'         },
      { id: 8,  name: 'Kozhikode'        },
      { id: 9,  name: 'Malappuram'       },
      { id: 10, name: 'Palakkad'         },
      { id: 11, name: 'Pathanamthitta'   },
      { id: 12, name: 'Thiruvananthapuram'},
      { id: 13, name: 'Thrissur'         },
      { id: 14, name: 'Wayanad'          },
    ],
    31: [
      { id: 1,  name: 'Ariyalur'        },
      { id: 2,  name: 'Chengalpattu'    },
      { id: 3,  name: 'Chennai'         },
      { id: 4,  name: 'Coimbatore'      },
      { id: 5,  name: 'Cuddalore'       },
      { id: 6,  name: 'Dharmapuri'      },
      { id: 7,  name: 'Dindigul'        },
      { id: 8,  name: 'Erode'           },
      { id: 9,  name: 'Kallakurichi'    },
      { id: 10, name: 'Kancheepuram'    },
      { id: 11, name: 'Kanyakumari'     },
      { id: 12, name: 'Karur'           },
      { id: 13, name: 'Krishnagiri'     },
      { id: 14, name: 'Madurai'         },
      { id: 15, name: 'Mayiladuthurai'  },
      { id: 16, name: 'Nagapattinam'    },
      { id: 17, name: 'Namakkal'        },
      { id: 18, name: 'Nilgiris'        },
      { id: 19, name: 'Perambalur'      },
      { id: 20, name: 'Pudukkottai'     },
      { id: 21, name: 'Ramanathapuram'  },
      { id: 22, name: 'Ranipet'         },
      { id: 23, name: 'Salem'           },
      { id: 24, name: 'Sivaganga'       },
      { id: 25, name: 'Tenkasi'         },
      { id: 26, name: 'Thanjavur'       },
      { id: 27, name: 'Theni'           },
      { id: 28, name: 'Thoothukudi'     },
      { id: 29, name: 'Tiruchirappalli' },
      { id: 30, name: 'Tirunelveli'     },
      { id: 31, name: 'Tirupathur'      },
      { id: 32, name: 'Tiruppur'        },
      { id: 33, name: 'Tiruvallur'      },
      { id: 34, name: 'Tiruvannamalai'  },
      { id: 35, name: 'Tiruvarur'       },
      { id: 36, name: 'Vellore'         },
      { id: 37, name: 'Viluppuram'      },
      { id: 38, name: 'Virudhunagar'    },
    ],
    32: [
      { id: 1, name: 'Karaikal'   },
      { id: 2, name: 'Mahe'       },
      { id: 3, name: 'Puducherry' },
      { id: 4, name: 'Yanam'      },
    ],
    33: [
      { id: 1, name: 'Nicobar'                  },
      { id: 2, name: 'North and Middle Andaman'  },
      { id: 3, name: 'South Andaman'             },
    ],
    34: [
      { id: 1,  name: 'Adilabad'                  },
      { id: 2,  name: 'Bhadradri Kothagudem'       },
      { id: 3,  name: 'Hanumakonda'                },
      { id: 4,  name: 'Hyderabad'                  },
      { id: 5,  name: 'Jagtial'                    },
      { id: 6,  name: 'Jangaon'                    },
      { id: 7,  name: 'Jayashankar Bhupalpally'    },
      { id: 8,  name: 'Jogulamba Gadwal'           },
      { id: 9,  name: 'Kamareddy'                  },
      { id: 10, name: 'Karimnagar'                 },
      { id: 11, name: 'Khammam'                    },
      { id: 12, name: 'Kumuram Bheem'              },
      { id: 13, name: 'Mahabubabad'                },
      { id: 14, name: 'Mahabubnagar'               },
      { id: 15, name: 'Mancherial'                 },
      { id: 16, name: 'Medak'                      },
      { id: 17, name: 'Medchal-Malkajgiri'         },
      { id: 18, name: 'Mulugu'                     },
      { id: 19, name: 'Nagarkurnool'               },
      { id: 20, name: 'Nalgonda'                   },
      { id: 21, name: 'Narayanpet'                 },
      { id: 22, name: 'Nirmal'                     },
      { id: 23, name: 'Nizamabad'                  },
      { id: 24, name: 'Peddapalli'                 },
      { id: 25, name: 'Rajanna Sircilla'           },
      { id: 26, name: 'Ranga Reddy'                },
      { id: 27, name: 'Sangareddy'                 },
      { id: 28, name: 'Siddipet'                   },
      { id: 29, name: 'Suryapet'                   },
      { id: 30, name: 'Vikarabad'                  },
      { id: 31, name: 'Wanaparthy'                 },
      { id: 32, name: 'Warangal Rural'             },
      { id: 33, name: 'Warangal Urban'             },
      { id: 34, name: 'Yadadri Bhuvanagiri'        },
    ],
    35: [
      { id: 1,  name: 'Alluri Sitharama Raju'           },
      { id: 2,  name: 'Anakapalli'                       },
      { id: 3,  name: 'Ananthapuramu'                    },
      { id: 4,  name: 'Annamayya'                        },
      { id: 5,  name: 'Bapatla'                          },
      { id: 6,  name: 'Chittoor'                         },
      { id: 7,  name: 'Dr. B.R. Ambedkar Konaseema'      },
      { id: 8,  name: 'East Godavari'                    },
      { id: 9,  name: 'Eluru'                            },
      { id: 10, name: 'Guntur'                           },
      { id: 11, name: 'Kakinada'                         },
      { id: 12, name: 'Krishna'                          },
      { id: 13, name: 'Kurnool'                          },
      { id: 14, name: 'Nandyal'                          },
      { id: 15, name: 'NTR'                              },
      { id: 16, name: 'Palnadu'                          },
      { id: 17, name: 'Parvathipuram Manyam'             },
      { id: 18, name: 'Prakasam'                         },
      { id: 19, name: 'Sri Potti Sriramulu Nellore'      },
      { id: 20, name: 'Sri Sathya Sai'                   },
      { id: 21, name: 'Srikakulam'                       },
      { id: 22, name: 'Tirupati'                         },
      { id: 23, name: 'Visakhapatnam'                    },
      { id: 24, name: 'Vizianagaram'                     },
      { id: 25, name: 'West Godavari'                    },
      { id: 26, name: 'YSR Kadapa'                       },
    ],
    36: [
      { id: 1, name: 'Kargil' },
      { id: 2, name: 'Leh'    },
    ],
  };

  groupSearchTerm = signal<string>('');
  groupSelectedDistance = signal<number>(1); // Default distance in kilometers

  getGroupsEventsPrograms(requestBody: NearbyGroupsRequestBody): Observable<GroupDetailsModel[]> {
    return this.http.post<GroupDetailsModel[]>(`${this.baseUrl}/groups`, requestBody);
  }

  getStates(): Observable<StateModel[]> {
    // return this.http.get<StateModel[]>('api/states');
    return new Observable(observer => {
      observer.next(this.states);
      observer.complete();
    });
  }

  getDistricts(stateId: number): Observable<DistrictModel[]> {
    // return this.http.get<DistrictModel[]>(`api/districts/${stateId}`);
    return new Observable(observer => {
      observer.next(this.districts[stateId] ?? []);
      observer.complete();
    });
  }

  getAreas(districtId: number): Observable<{ id: number; name: string }[]> {
    return this.http.get<{ id: number; name: string }[]>(`api/areas/${districtId}`);
  }

  createSamiti(payload: CreateSamitiModel): Observable<{ id: number; message: string }> {
    return this.http.post<{ id: number; message: string }>(`${this.baseUrl}/groups`, payload);
  }
}
