import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../environments/environment';
import { EventType, ProgramType, GroupDetailsModel, StateModel, DistrictModel, CreateSamitiModel } from '../models/home.model';
import { Observable } from 'rxjs';
import { signal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class HomeService {
  private apiUrl = 'api/data'; // Replace with your actual API endpoint
  private baseUrl = environment.apiBaseUrl;

  constructor(private http: HttpClient) {}

  // Reference point as "current location": 21.2300, 81.4500 (Raipur area)
  // Groups are spread from 100m to 5km from this point
  // Events are within 200m of their group location
  samitiGroups: GroupDetailsModel[] = [
    {
      "id": 1,
      "groupId": "ANM_1",
      "title": "Azad Navyuvak Mandal",
      "locationCords": { "lat": 21.2310, "long": 81.4508 },  // ~150m from user
      "area": "Kumhari",
      "since": 2018,
      "description": "Azad Navyuvak Mandal is a vibrant youth organization based in Raipur, Chhattisgarh. Founded in 2018, the group has quickly become a hub for young people passionate about community service, cultural activities, and social change. With a focus on empowering youth and fostering a sense of unity, Azad Navyuvak Mandal organizes a wide range of events throughout the year, including festivals, charity drives, educational workshops, and sports tournaments. The group is known for its inclusive and energetic approach, attracting members from diverse backgrounds who share a common goal of making a positive impact in their community.",
      "contactNumbers": ["9876543210", "9123456780"],
      "logo": "https://picsum.photos/seed/anm-logo/200/200",
      "favourite": true,
      "admins": [],
      "events": [
        {
          "id": 101,
          "title": "Ganesh Utsav 2026",
          "type" : EventType.SPORTS,
          "year_count": 5,
          "start_date": "2026-03-19",
          "end_date": "2026-12-31",
          "locationCords": { "lat": 21.2312, "long": 81.4510 },  // ~180m from group
          "photos": [
            "https://picsum.photos/seed/ganesh-utsav/800/500",
            "https://picsum.photos/seed/ganesh-utsav-2/800/500"
          ],
          "programs": [
            { "id": 101001, 'description' : "Start the day with divine blessings as devotees gather at dawn for the sacred Prabhat Aarati, filling the air with hymns and incense.", "title": "Prabhat Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-04-10", "from_time": "07:00", "to_time": "21:00", "photos": ["https://picsum.photos/seed/program-101001-1/800/500", "https://picsum.photos/seed/program-101001-2/800/500"], "locationCords": { "lat": 21.2312, "long": 81.4510 } },
            { "id": 101002, 'description' : "Witness the sacred installation ceremony of Lord Ganesha's idol, accompanied by Vedic chants and a purifying hawan ritual.", "title": "Sthapana Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-03-19", "from_time": "07:00", "to_time": "21:30", "photos": ["https://picsum.photos/seed/program-101002-1/800/500", "https://picsum.photos/seed/program-101002-2/800/500"], "locationCords": { "lat": 21.2313, "long": 81.4511 } },
            { "id": 101003, 'description' : "An engaging session for children to learn about values, culture, and the teachings of Lord Ganesha through stories and activities.", "title": "Bal Sanskar Sabha", "type": ProgramType.BHANDARA, "date": "2026-03-19", "from_time": "07:00", "to_time": "21:00", "photos": ["https://picsum.photos/seed/program-101003-1/800/500", "https://picsum.photos/seed/program-101003-2/800/500"], "locationCords": { "lat": 21.2311, "long": 81.4509 } },
            { "id": 101004, 'description' : "Women from the community come together for a soul-stirring evening of devotional bhajans and kirtan in honor of Lord Ganesha.", "title": "Mahila Bhajan Sandhya", "type": ProgramType.CULTURAL, "date": "2026-03-19", "from_time": "07:30", "to_time": "21:00", "photos": ["https://picsum.photos/seed/program-101004-1/800/500", "https://picsum.photos/seed/program-101004-2/800/500"], "locationCords": { "lat": 21.2312, "long": 81.4511 } },
            { "id": 101005, 'description' : "A grand community feast distributing blessed prasad to all devotees, symbolizing unity and divine grace of Lord Ganesha.", "title": "Mahaprasad Vitran", "type": ProgramType.BHANDARA, "date": "2026-02-09", "from_time": "07:23", "to_time": "21:30", "photos": ["https://picsum.photos/seed/program-101005-1/800/500", "https://picsum.photos/seed/program-101005-2/800/500"], "locationCords": { "lat": 21.2313, "long": 81.4510 } },
            { "id": 101006, 'description' : "The grand procession for the immersion of Lord Ganesha's idol, featuring music, dance, and heartfelt farewells from the entire community.", "title": "Ganesh Visarjan Yatra", "type": ProgramType.SPIRITUAL, "date": "2026-02-24", "from_time": "21:30", "to_time": "20:30", "photos": ["https://picsum.photos/seed/program-101006-1/800/500", "https://picsum.photos/seed/program-101006-2/800/500"], "locationCords": { "lat": 21.2311, "long": 81.4510 } }
          ],
          "description": "Celebrate the vibrant festival of Ganesh Utsav with us! Join us for 10 days of cultural performances, community feasts, and spiritual activities as we honor Lord Ganesha. The event will feature traditional music and dance, delicious food stalls, and a grand procession on the final day. Don't miss this opportunity to experience the rich cultural heritage of Raipur and connect with fellow community members in a joyous celebration!"
        },
        {
          "id": 102,
          "title": "Blood Donation Camp",
          "type" : EventType.OTHER,
          "year_count": 2,
          "start_date": "2026-03-12",
          "end_date": "2026-03-14",
          "locationCords": { "lat": 21.2308, "long": 81.4506 },  // ~120m from group
          "photos": [
            "https://picsum.photos/seed/blood-donation/800/500",
            "https://picsum.photos/seed/blood-donation-2/800/500"
          ],
          "programs": [
            { "id": 102001, 'description' : "The camp begins with a short prayer ceremony to seek blessings for the health of all donors and recipients of donated blood.", "title": "Shubh Aarambh Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-03-13", "from_time": "08:00", "to_time": "08:30", "photos": ["https://picsum.photos/seed/program-102001-1/800/500", "https://picsum.photos/seed/program-102001-2/800/500"], "locationCords": { "lat": 21.2308, "long": 81.4506 } },
            { "id": 102002, 'description' : "A continuous health desk staffed by medical professionals providing consultations, blood pressure checks, and health tips throughout the day.", "title": "Health Desk", "type": ProgramType.BHANDARA, "date": "2026-03-14", "from_time": "00:00", "to_time": "23:59", "photos": ["https://picsum.photos/seed/program-102002-1/800/500", "https://picsum.photos/seed/program-102002-2/800/500"], "locationCords": { "lat": 21.2309, "long": 81.4507 } },
            { "id": 102003, 'description' : "A nutritious meal provided to all blood donors as post-donation care, prepared lovingly by community volunteers to aid recovery.", "title": "Seva Bhandara", "type": ProgramType.BHANDARA, "date": "2026-03-16", "from_time": "12:00", "to_time": "14:00", "photos": ["https://picsum.photos/seed/program-102003-1/800/500", "https://picsum.photos/seed/program-102003-2/800/500"], "locationCords": { "lat": 21.2307, "long": 81.4505 } },
            { "id": 102004, 'description' : "An evening prayer to thank the divine for inspiring so many community members to donate blood and save precious lives.", "title": "Evening Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-03-13", "from_time": "18:00", "to_time": "18:45", "photos": ["https://picsum.photos/seed/program-102004-1/800/500", "https://picsum.photos/seed/program-102004-2/800/500"], "locationCords": { "lat": 21.2308, "long": 81.4507 } },
            { "id": 102005, 'description' : "The closing ceremony of the camp with a hawan to bless all donors and pray for the speedy recovery of those in need.", "title": "Samapan Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-03-14", "from_time": "16:00", "to_time": "17:30", "photos": ["https://picsum.photos/seed/program-102005-1/800/500", "https://picsum.photos/seed/program-102005-2/800/500"], "locationCords": { "lat": 21.2309, "long": 81.4506 } }
          ],
          "description": "Save lives by donating blood! Our community blood donation camp provides a safe and hygienic environment for blood donors. Every donation can save up to three lives. Medical professionals will conduct health checks, and all donors will receive refreshments and certificates of appreciation. Join us in this noble cause!"
        },
        {
          "id": 103,
          "title": "Cricket League",
          "type" : EventType.SPORTS,
          "year_count": 10,
          "start_date": "2026-02-01",
          "end_date": "2026-02-12",
          "locationCords": { "lat": 21.2311, "long": 81.4512 },  // ~150m from group
          "photos": [
            "https://picsum.photos/seed/cricket-league/800/500",
            "https://picsum.photos/seed/cricket-league-2/800/500"
          ],
          "programs": [
            { "id": 103001, 'description' : "The cricket league kicks off with an exciting opening ceremony featuring team introductions, flag hoisting, and a march-past by all players.", "title": "Opening Ceremony", "type": ProgramType.SPIRITUAL, "date": "2026-02-01", "from_time": "09:00", "to_time": "10:00", "photos": ["https://picsum.photos/seed/program-103001-1/800/500", "https://picsum.photos/seed/program-103001-2/800/500"], "locationCords": { "lat": 21.2311, "long": 81.4512 } },
            { "id": 103002, 'description' : "A sacred hawan where all team captains take a pledge of sportsmanship and fair play before the tournament officially begins.", "title": "Team Pledge Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-02-01", "from_time": "10:30", "to_time": "11:15", "photos": ["https://picsum.photos/seed/program-103002-1/800/500", "https://picsum.photos/seed/program-103002-2/800/500"], "locationCords": { "lat": 21.2312, "long": 81.4513 } },
            { "id": 103003, 'description' : "A mid-tournament community feast for all players, coaches, and volunteers to recharge and build camaraderie during the league.", "title": "Players Bhandara", "type": ProgramType.BHANDARA, "date": "2026-02-06", "from_time": "14:00", "to_time": "15:30", "photos": ["https://picsum.photos/seed/program-103003-1/800/500", "https://picsum.photos/seed/program-103003-2/800/500"], "locationCords": { "lat": 21.2310, "long": 81.4511 } },
            { "id": 103004, 'description' : "An exclusive meet-and-greet session where fans interact with their favorite players, followed by distribution of prasad and snacks.", "title": "Fan Meet Prasad", "type": ProgramType.BHANDARA, "date": "2026-02-10", "from_time": "17:00", "to_time": "18:00", "photos": ["https://picsum.photos/seed/program-103004-1/800/500", "https://picsum.photos/seed/program-103004-2/800/500"], "locationCords": { "lat": 21.2311, "long": 81.4513 } },
            { "id": 103005, 'description' : "The grand finale featuring the championship match, trophy presentation, and a ceremonial visarjan to conclude the 12-day tournament.", "title": "Final Award Visarjan", "type": ProgramType.SPIRITUAL, "date": "2026-02-12", "from_time": "18:00", "to_time": "20:00", "photos": ["https://picsum.photos/seed/program-103005-1/800/500", "https://picsum.photos/seed/program-103005-2/800/500"], "locationCords": { "lat": 21.2312, "long": 81.4512 } }
          ],
          "description": "Experience thrilling cricket action in our annual league tournament! Teams from across the city will compete in this exciting 12-day event featuring matches, skill demonstrations, and awards for outstanding performances. Whether you're a player or a spectator, this is the ultimate cricket celebration!"
        }
      ]
    },
    {
      "id": 2,
      "groupId": "ESB_2",
      "title": "Ekta Samiti Bhilai",
      "locationCords": { "lat": 21.2345, "long": 81.4520 },  // ~550m from user
      "area": "Charoda",
      "since": 2010,
      "description": "Ekta Samiti Bhilai promotes community harmony and organizes cultural events that bring people together in celebration and solidarity.",
      "contactNumbers": ["9876123456", "9123456781"],
      "logo": "https://picsum.photos/seed/esb-logo/200/200",
      "favourite": false,
      "admins": [],
      "events": [
        {
          "id": 201,
          "title": "Durga Puja 2025",
          "type" : EventType.PUJA,
          "year_count": 51,
          "start_date": "2026-03-12",
          "end_date": "2026-03-15",
          "locationCords": { "lat": 21.2347, "long": 81.4522 },  // ~160m from group
          "photos": [
            "https://picsum.photos/seed/durga-puja/800/500",
            "https://picsum.photos/seed/durga-puja-2/800/500"
          ],
          "programs": [
            { "id": 201001, 'description' : "The festival begins with the auspicious Kalash Sthapana ritual, invoking Goddess Durga's divine presence and seeking her blessings for all devotees.", "title": "Kalash Sthapana", "type": ProgramType.SPIRITUAL, "date": "2026-03-12", "from_time": "06:30", "to_time": "08:00", "photos": ["https://picsum.photos/seed/program-201001-1/800/500", "https://picsum.photos/seed/program-201001-2/800/500"], "locationCords": { "lat": 21.2347, "long": 81.4522 } },
            { "id": 201002, 'description' : "Young girls are worshipped as manifestations of Goddess Durga in this deeply touching ceremony that celebrates feminine divinity.", "title": "Kumari Pujan", "type": ProgramType.SPIRITUAL, "date": "2026-03-12", "from_time": "10:00", "to_time": "11:30", "photos": ["https://picsum.photos/seed/program-201002-1/800/500", "https://picsum.photos/seed/program-201002-2/800/500"], "locationCords": { "lat": 21.2348, "long": 81.4523 } },
            { "id": 201003, 'description' : "A grand community feast open to all, serving traditional festive food as a symbol of equality and divine generosity during Durga Puja.", "title": "Maha Bhandara", "type": ProgramType.BHANDARA, "date": "2026-03-16", "from_time": "11:00", "to_time": "19:00", "photos": ["https://picsum.photos/seed/program-201003-1/800/500", "https://picsum.photos/seed/program-201003-2/800/500"], "locationCords": { "lat": 21.2346, "long": 81.4521 } },
            { "id": 201004, 'description' : "The mesmerizing evening aarati with lamps, bells, and devotional songs creates a deeply spiritual atmosphere for all devotees.", "title": "Sandhya Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-03-16", "from_time": "14:00", "to_time": "20:00", "photos": ["https://picsum.photos/seed/program-201004-1/800/500", "https://picsum.photos/seed/program-201004-2/800/500"], "locationCords": { "lat": 21.2347, "long": 81.4523 } },
            { "id": 201005, 'description' : "The grand farewell procession for Goddess Durga, with thousands joining the colorful parade through the streets to the immersion site.", "title": "Visarjan Shobha Yatra", "type": ProgramType.CRICKET, "date": "2026-03-15", "from_time": "16:00", "to_time": "20:00", "photos": ["https://picsum.photos/seed/program-201005-1/800/500", "https://picsum.photos/seed/program-201005-2/800/500"], "locationCords": { "lat": 21.2348, "long": 81.4522 } }
          ],
          "description": "Join us for the most revered festival celebration! This 51-year-old tradition brings together thousands of devotees for cultural performances, traditional feasts, and spiritual ceremonies to honor Goddess Durga. Experience intricate decorations, elaborate pujas, and community bonding at its finest!"
        },
        {
          "id": 202,
          "title": "Garba Night",
          "year_count": 5,
          "type": EventType.PUJA,
          "start_date": "2025-12-15",
          "end_date": "2025-12-25",
          "locationCords": { "lat": 21.2343, "long": 81.4518 },  // ~140m from group
          "photos": [
            "https://picsum.photos/seed/garba-night/800/500",
            "https://picsum.photos/seed/garba-night-2/800/500"
          ],
          "programs": [
            { "id": 202001, 'description' : "The Garba celebration begins with a divine aarati to invoke Goddess Amba's blessings before the colorful dance festivities commence.", "title": "Garba Opening Aarati", "type": ProgramType.SPIRITUAL, "date": "2025-12-15", "from_time": "18:30", "to_time": "19:00", "photos": ["https://picsum.photos/seed/program-202001-1/800/500", "https://picsum.photos/seed/program-202001-2/800/500"], "locationCords": { "lat": 21.2343, "long": 81.4518 } },
            { "id": 202002, 'description' : "An interactive workshop for beginners to learn the art of Dandiya Raas, led by experienced dance instructors in a festive atmosphere.", "title": "Dandiya Workshop", "type": ProgramType.CULTURAL, "date": "2025-12-15", "from_time": "19:15", "to_time": "20:15", "photos": ["https://picsum.photos/seed/program-202002-1/800/500", "https://picsum.photos/seed/program-202002-2/800/500"], "locationCords": { "lat": 21.2344, "long": 81.4519 } },
            { "id": 202003, 'description' : "Sweet prasad is distributed to all participants as a symbol of Goddess Amba's blessings during the joyful festive celebration.", "title": "Community Prasad Vitran", "type": ProgramType.BHANDARA, "date": "2025-12-20", "from_time": "21:00", "to_time": "22:00", "photos": ["https://picsum.photos/seed/program-202003-1/800/500", "https://picsum.photos/seed/program-202003-2/800/500"], "locationCords": { "lat": 21.2342, "long": 81.4517 } },
            { "id": 202004, 'description' : "Young dancers take center stage in an energetic Garba round, showcasing their vibrant attire and gracefully synchronized movements.", "title": "Youth Garba Round", "type": ProgramType.CULTURAL, "date": "2025-12-22", "from_time": "20:00", "to_time": "21:30", "photos": ["https://picsum.photos/seed/program-202004-1/800/500", "https://picsum.photos/seed/program-202004-2/800/500"], "locationCords": { "lat": 21.2343, "long": 81.4519 } },
            { "id": 202005, 'description' : "The festival concludes with a grand feast celebrating the spirit of togetherness and community bonding, sending everyone home with a full heart.", "title": "Grand Finale Bhandara", "type": ProgramType.BHANDARA, "date": "2025-12-25", "from_time": "20:30", "to_time": "22:30", "photos": ["https://picsum.photos/seed/program-202005-1/800/500", "https://picsum.photos/seed/program-202005-2/800/500"], "locationCords": { "lat": 21.2344, "long": 81.4518 } }
          ],
          "description": "Dance into the festive season with our vibrant Garba Night! This traditional circular dance celebrates the joy of togetherness. Come dressed in colorful attire to participate in group dances, enjoy music, and connect with the community in a fun and energetic atmosphere!"
        }
      ]
    },
    {
      "id": 3,
      "groupId": "NSM_3",
      "title": "Navjivan Samaj Mandal",
      "locationCords": { "lat": 21.2420, "long": 81.4580 },  // ~1.5km from user
      "area": "Bhilai 3",
      "since": 2015,
      "description": "Navjivan Samaj Mandal works towards social welfare and youth empowerment through various educational and cultural programs.",
      "contactNumbers": ["9876543211", "9123456782"],
      "logo": "https://picsum.photos/seed/nsm-logo/200/200",
      "favourite": true,
      "admins": [],
      "events": [
        {
          "id": 301,
          "title": "Holi Celebration",
          "year_count": 8,
          "type" : EventType.FESTIVAL,
          "start_date": "2026-03-20",
          "end_date": "2026-03-21",
          "locationCords": { "lat": 21.2422, "long": 81.4578 },  // ~180m from group
          "photos": [
            "https://picsum.photos/seed/holi/800/500",
            "https://picsum.photos/seed/holi-2/800/500"
          ],
          "programs": [
            { "id": 301001, 'description' : "The Holi celebration begins with a spiritual aarati and community prayers, setting a joyful and auspicious tone for the festival of colors.", "title": "Holi Milan Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-03-20", "from_time": "09:00", "to_time": "09:45", "photos": ["https://picsum.photos/seed/program-301001-1/800/500", "https://picsum.photos/seed/program-301001-2/800/500"], "locationCords": { "lat": 21.2422, "long": 81.4578 } },
            { "id": 301002, 'description' : "A festive community meal featuring traditional Holi delicacies like gujiya, thandai, and puranpoli, shared with everyone in attendance.", "title": "Rangotsav Bhandara", "type": ProgramType.BHANDARA, "date": "2026-03-20", "from_time": "13:00", "to_time": "15:00", "photos": ["https://picsum.photos/seed/program-301002-1/800/500", "https://picsum.photos/seed/program-301002-2/800/500"], "locationCords": { "lat": 21.2423, "long": 81.4579 } },
            { "id": 301003, 'description' : "Local artists perform traditional Chhattisgarhi folk dances, bringing the rich and vibrant cultural heritage of the region to life.", "title": "Folk Dance Program", "type": ProgramType.CULTURAL, "date": "2026-03-20", "from_time": "13:00", "to_time": "15:00", "photos": ["https://picsum.photos/seed/program-301003-1/800/500", "https://picsum.photos/seed/program-301003-2/800/500"], "locationCords": { "lat": 21.2421, "long": 81.4577 } },
            { "id": 301004, 'description' : "A purifying hawan ceremony as the sun sets on Holi day, symbolizing the timeless victory of good over evil and light over darkness.", "title": "Evening Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-03-20", "from_time": "18:30", "to_time": "19:30", "photos": ["https://picsum.photos/seed/program-301004-1/800/500", "https://picsum.photos/seed/program-301004-2/800/500"], "locationCords": { "lat": 21.2422, "long": 81.4579 } }
          ],
          "description": "Celebrate the festival of colors with our grand Holi event! Join us for music, dance, and colorful fun as we welcome spring with joy and enthusiasm."
        },
        {
          "id": 302,
          "title": "Youth Sports Meet",
          "type" : EventType.SPORTS,
          "year_count": 3,
          "start_date": "2026-04-10",
          "end_date": "2026-04-15",
          "locationCords": { "lat": 21.2418, "long": 81.4582 },  // ~150m from group
          "photos": [
            "https://picsum.photos/seed/sports/800/500",
            "https://picsum.photos/seed/sports-2/800/500"
          ],
          "programs": [
            { "id": 302001, 'description' : "The sports meet begins with an inspiring torch rally through the streets, symbolizing the Olympic spirit and the boundless energy of youth.", "title": "Torch Rally", "type": ProgramType.OTHER, "date": "2026-04-10", "from_time": "08:00", "to_time": "09:00", "photos": ["https://picsum.photos/seed/program-302001-1/800/500", "https://picsum.photos/seed/program-302001-2/800/500"], "locationCords": { "lat": 21.2418, "long": 81.4582 } },
            { "id": 302002, 'description' : "A sacred hawan ceremony to seek blessings for all athletes, praying for their safety and best performance throughout the sports event.", "title": "Opening Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-04-10", "from_time": "09:30", "to_time": "10:15", "photos": ["https://picsum.photos/seed/program-302002-1/800/500", "https://picsum.photos/seed/program-302002-2/800/500"], "locationCords": { "lat": 21.2419, "long": 81.4583 } },
            { "id": 302003, 'description' : "A specially curated nutritious meal for all athletes to maintain energy and stamina during the mid-tournament phase of the sports meet.", "title": "Athlete Nutrition Prasad", "type": ProgramType.BHANDARA, "date": "2026-04-12", "from_time": "12:30", "to_time": "13:30", "photos": ["https://picsum.photos/seed/program-302003-1/800/500", "https://picsum.photos/seed/program-302003-2/800/500"], "locationCords": { "lat": 21.2417, "long": 81.4581 } },
            { "id": 302004, 'description' : "Experienced athletes and coaches share insights on sports psychology, career in sports, and valuable life skills with young participants.", "title": "Mentor Talk", "type": ProgramType.CULTURAL, "date": "2026-04-14", "from_time": "17:00", "to_time": "18:00", "photos": ["https://picsum.photos/seed/program-302004-1/800/500", "https://picsum.photos/seed/program-302004-2/800/500"], "locationCords": { "lat": 21.2418, "long": 81.4583 } },
            { "id": 302005, 'description' : "The sports meet concludes with trophy distribution, felicitation of outstanding performers, and a closing prayer for all participants.", "title": "Closing Ceremony", "type": ProgramType.SPIRITUAL, "date": "2026-04-15", "from_time": "18:00", "to_time": "19:30", "photos": ["https://picsum.photos/seed/program-302005-1/800/500", "https://picsum.photos/seed/program-302005-2/800/500"], "locationCords": { "lat": 21.2419, "long": 81.4582 } }
          ],
          "description": "Annual sports meet featuring various competitions including cricket, volleyball, badminton, and athletics for youth from across the city."
        }
      ]
    },
    {
      "id": 4,
      "groupId": "RSYC_4",
      "title": "Rising Star Youth Club",
      "locationCords": { "lat": 21.2510, "long": 81.4620 },  // ~2.8km from user
      "area": "Jamul",
      "since": 2021,
      "description": "Rising Star Youth Club nurtures young talent through sports, education, and personality development programs.",
      "contactNumbers": ["9876456789", "9123456784"],
      "logo": "https://picsum.photos/seed/rsyc-logo/200/200",
      "favourite": false,
      "admins": [],
      "events": [
        {
          "id": 401,
          "title": "Dance Competition",
          "type" : EventType.SPORTS,
          "year_count": 4,
          "start_date": "2026-05-15",
          "end_date": "2026-05-25",
          "locationCords": { "lat": 21.2512, "long": 81.4618 },  // ~170m from group
          "photos": [
            "https://picsum.photos/seed/dance-competition/800/500",
            "https://picsum.photos/seed/dance-competition-2/800/500"
          ],
          "programs": [
            { "id": 401001, 'description' : "The stage is consecrated with a poojan ceremony, invoking the blessings of Goddess Saraswati for all the aspiring performers taking part.", "title": "Stage Poojan", "type": ProgramType.SPIRITUAL, "date": "2026-05-15", "from_time": "10:00", "to_time": "11:00", "photos": ["https://picsum.photos/seed/program-401001-1/800/500", "https://picsum.photos/seed/program-401001-2/800/500"], "locationCords": { "lat": 21.2512, "long": 81.4618 } },
            { "id": 401002, 'description' : "Young dancers aged 8-14 showcase their talent in various classical and folk dance forms in this exciting junior category showcase round.", "title": "Junior Category Round", "type": ProgramType.CULTURAL, "date": "2026-05-15", "from_time": "16:00", "to_time": "18:00", "photos": ["https://picsum.photos/seed/program-401002-1/800/500", "https://picsum.photos/seed/program-401002-2/800/500"], "locationCords": { "lat": 21.2513, "long": 81.4619 } },
            { "id": 401003, 'description' : "A community meal served to all audience members and participants, ensuring everyone feels welcomed, nourished, and celebrated at the event.", "title": "Audience Bhandara", "type": ProgramType.BHANDARA, "date": "2026-05-20", "from_time": "14:00", "to_time": "15:30", "photos": ["https://picsum.photos/seed/program-401003-1/800/500", "https://picsum.photos/seed/program-401003-2/800/500"], "locationCords": { "lat": 21.2511, "long": 81.4617 } },
            { "id": 401004, 'description' : "The best performers from earlier rounds compete in the spectacular semi-finals, raising the artistic bar and delighting the audience.", "title": "Semi Final Showcase", "type": ProgramType.CULTURAL, "date": "2026-05-23", "from_time": "18:30", "to_time": "20:00", "photos": ["https://picsum.photos/seed/program-401004-1/800/500", "https://picsum.photos/seed/program-401004-2/800/500"], "locationCords": { "lat": 21.2512, "long": 81.4619 } },
            { "id": 401005, 'description' : "The champions are felicitated with trophies and certificates, followed by a celebratory puja and distribution of prasad to all performers.", "title": "Winner Celebration", "type": ProgramType.SPIRITUAL, "date": "2026-05-25", "from_time": "19:00", "to_time": "21:00", "photos": ["https://picsum.photos/seed/program-401005-1/800/500", "https://picsum.photos/seed/program-401005-2/800/500"], "locationCords": { "lat": 21.2513, "long": 81.4618 } }
          ],
          "description": "Showcase your dance talent in our inter-city dance competition featuring various styles from classical to contemporary!"
        }
      ]
    },
    {
      "id": 5,
      "groupId": "USM_5",
      "title": "Unity Seva Mandal",
      "locationCords": { "lat": 21.2640, "long": 81.4710 },  // ~4.5km from user
      "area": "Ahiwara",
      "since": 2012,
      "description": "Unity Seva Mandal is dedicated to community service, organizing health camps, educational programs, and social welfare activities.",
      "contactNumbers": ["9876789012", "9123456785"],
      "logo": "https://picsum.photos/seed/usm-logo/200/200",
      "favourite": true,
      "admins": [],
      "events": [
        {
          "id": 501,
          "title": "Free Health Camp",
          "type" : EventType.OTHER,
          "year_count": 11,
          "start_date": "2026-06-01",
          "end_date": "2026-06-05",
          "locationCords": { "lat": 21.2638, "long": 81.4708 },  // ~140m from group
          "photos": [
            "https://picsum.photos/seed/health-camp/800/500",
            "https://picsum.photos/seed/health-camp-2/800/500"
          ],
          "programs": [
            { "id": 501001, 'description' : "The health camp opens with a prayer for good health and wellness, encouraging community members to take proactive charge of their well-being.", "title": "Health Sankalp Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-06-01", "from_time": "08:30", "to_time": "09:00", "photos": ["https://picsum.photos/seed/program-501001-1/800/500", "https://picsum.photos/seed/program-501001-2/800/500"], "locationCords": { "lat": 21.2638, "long": 81.4708 } },
            { "id": 501002, 'description' : "Expert doctors deliver engaging talks on preventive healthcare, nutrition, and common lifestyle diseases to educate and empower the community.", "title": "Health Talk Session", "type": ProgramType.CULTURAL, "date": "2026-06-01", "from_time": "10:00", "to_time": "11:00", "photos": ["https://picsum.photos/seed/program-501002-1/800/500", "https://picsum.photos/seed/program-501002-2/800/500"], "locationCords": { "lat": 21.2639, "long": 81.4709 } },
            { "id": 501003, 'description' : "A nutritious meal provided to patients and caregivers attending the health camp, prepared with hygiene and care by community volunteers.", "title": "Patient Meal Bhandara", "type": ProgramType.BHANDARA, "date": "2026-06-03", "from_time": "13:00", "to_time": "14:30", "photos": ["https://picsum.photos/seed/program-501003-1/800/500", "https://picsum.photos/seed/program-501003-2/800/500"], "locationCords": { "lat": 21.2637, "long": 81.4707 } },
            { "id": 501004, 'description' : "An open forum where residents can ask health-related questions directly to specialists, fostering awareness and preventive healthcare habits.", "title": "Doctor Q&A Camp", "type": ProgramType.CULTURAL, "date": "2026-06-04", "from_time": "16:00", "to_time": "17:00", "photos": ["https://picsum.photos/seed/program-501004-1/800/500", "https://picsum.photos/seed/program-501004-2/800/500"], "locationCords": { "lat": 21.2638, "long": 81.4709 } },
            { "id": 501005, 'description' : "The camp concludes with a hawan ceremony praying for the health, longevity, and prosperity of all community members and their families.", "title": "Samapan Hawan", "type": ProgramType.SPIRITUAL, "date": "2026-06-05", "from_time": "17:00", "to_time": "18:00", "photos": ["https://picsum.photos/seed/program-501005-1/800/500", "https://picsum.photos/seed/program-501005-2/800/500"], "locationCords": { "lat": 21.2639, "long": 81.4708 } }
          ],
          "description": "Free health checkup camp providing medical consultations, blood tests, and health awareness sessions for the community."
        },
        {
          "id": 502,
          "title": "Educational Workshop",
          "type" : EventType.OTHER,
          "year_count": 6,
          "start_date": "2026-07-10",
          "end_date": "2026-07-12",
          "locationCords": { "lat": 21.2642, "long": 81.4712 },  // ~160m from group
          "photos": [
            "https://picsum.photos/seed/workshop/800/500",
            "https://picsum.photos/seed/workshop-2/800/500"
          ],
          "programs": [
            { "id": 502001, 'description' : "The educational workshop is inaugurated with an aarati, seeking blessings of wisdom and learning for all participants and facilitators.", "title": "Workshop Inaugural Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-07-10", "from_time": "09:30", "to_time": "10:00", "photos": ["https://picsum.photos/seed/program-502001-1/800/500", "https://picsum.photos/seed/program-502001-2/800/500"], "locationCords": { "lat": 21.2642, "long": 81.4712 } },
            { "id": 502002, 'description' : "Hands-on skill development activities covering digital literacy, communication skills, and vocational training for the participating youth.", "title": "Skill Lab Session", "type": ProgramType.CULTURAL, "date": "2026-07-10", "from_time": "11:00", "to_time": "12:30", "photos": ["https://picsum.photos/seed/program-502002-1/800/500", "https://picsum.photos/seed/program-502002-2/800/500"], "locationCords": { "lat": 21.2643, "long": 81.4713 } },
            { "id": 502006, 'description' : "A warm and hearty meal for all volunteers who have dedicated their time and effort to making this educational workshop a success.", "title": "Volunteer Bhandara", "type": ProgramType.BHANDARA, "date": "2026-07-10", "from_time": "11:00", "to_time": "12:30", "photos": ["https://picsum.photos/seed/program-502006-1/800/500", "https://picsum.photos/seed/program-502006-2/800/500"], "locationCords": { "lat": 21.2641, "long": 81.4711 } },
            { "id": 502003, 'description' : "Blessed prasad is distributed to all students as a token of encouragement and divine blessings for their continued academic journey.", "title": "Student Prasad Vitran", "type": ProgramType.BHANDARA, "date": "2026-07-11", "from_time": "12:30", "to_time": "13:30", "photos": ["https://picsum.photos/seed/program-502003-1/800/500", "https://picsum.photos/seed/program-502003-2/800/500"], "locationCords": { "lat": 21.2642, "long": 81.4713 } },
            { "id": 502004, 'description' : "Industry experts and career counselors guide students on education pathways, scholarship opportunities, and smart career planning choices.", "title": "Career Guidance Panel", "type": ProgramType.CULTURAL, "date": "2026-07-11", "from_time": "15:00", "to_time": "16:00", "photos": ["https://picsum.photos/seed/program-502004-1/800/500", "https://picsum.photos/seed/program-502004-2/800/500"], "locationCords": { "lat": 21.2643, "long": 81.4712 } },
            { "id": 502005, 'description' : "The workshop concludes with a heartfelt closing ceremony honoring students, mentors, and volunteers for their remarkable contributions.", "title": "Closing Visarjan Program", "type": ProgramType.SPIRITUAL, "date": "2026-07-12", "from_time": "17:30", "to_time": "18:30", "photos": ["https://picsum.photos/seed/program-502005-1/800/500", "https://picsum.photos/seed/program-502005-2/800/500"], "locationCords": { "lat": 21.2641, "long": 81.4712 } }
          ],
          "description": "Educational workshop for students covering career guidance, personality development, and skill enhancement programs."
        }
      ]
    },
    {
      "id": 10,
      "groupId": "VNC_10",
      "title": "Very Nearby Club",
      "locationCords": { "lat": 21.2301, "long": 81.4501 },  // ~120m from user (very close)
      "area": "Kumhari",
      "since": 2025,
      "description": "A community club located very close to you, perfect for quick meetups and local events.",
      "contactNumbers": ["9000000000"],
      "logo": "https://picsum.photos/seed/nearby-test/200/200",
      "favourite": false,
      "admins": [],
      "events": [
        {
          "id": 1001,
          "title": "Weekend Meetup",
          "type" : EventType.OTHER,
          "year_count": 1,
          "start_date": "2026-03-12",
          "end_date": "2026-03-13",
          "locationCords": { "lat": 21.2301, "long": 81.4501 },  // Same as group location
          "photos": ["https://picsum.photos/seed/test-event/800/500"],
          "programs": [
            { "id": 1001001, 'description' : "The weekend meetup begins with a peaceful morning aarati, connecting neighborhood members through shared spiritual practice and community prayer.", "title": "Morning Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-03-16", "from_time": "07:00", "to_time": "08:00", "photos": ["https://picsum.photos/seed/program-1001001-1/800/500", "https://picsum.photos/seed/program-1001001-2/800/500"], "locationCords": { "lat": 21.2301, "long": 81.4501 } },
            { "id": 1001002, 'description' : "A day-long open bhandara welcoming all neighborhood residents to enjoy home-cooked meals, exchange ideas, and strengthen community bonds.", "title": "Community Bhandara", "type": ProgramType.BHANDARA, "date": "2026-03-12", "from_time": "00:00", "to_time": "23:59", "photos": ["https://picsum.photos/seed/program-1001002-1/800/500", "https://picsum.photos/seed/program-1001002-2/800/500"], "locationCords": { "lat": 21.2302, "long": 81.4502 } }
          ],
          "description": "Casual weekend meetup for community members to connect, share ideas, and plan future activities together."
        }
      ]
    },
    {
      "id": 11,
      "groupId": "DSS_11",
      "title": "Bemetera Seva Sangh",
      "locationCords": { "lat": 21.6480, "long": 81.4500 },
      "area": "Bemetara",
      "since": 2016,
      "description": "Durg Seva Sangh is a long-running community organization known for devotional gatherings, public service programs, and large-scale annual celebrations that attract members from across the district.",
      "contactNumbers": ["9876500011", "9123400011"],
      "logo": "https://picsum.photos/seed/dss-logo/200/200",
      "favourite": false,
      "admins": [],
      "events": [
        {
          "id": 1101,
          "title": "Sharad Mahotsav",
          "type": EventType.FESTIVAL,
          "year_count": 14,
          "start_date": "2026-10-18",
          "end_date": "2026-10-20",
          "locationCords": { "lat": 21.6482, "long": 81.4503 },
          "photos": [
            "https://picsum.photos/seed/sharad-mahotsav/800/500",
            "https://picsum.photos/seed/sharad-mahotsav-2/800/500"
          ],
          "programs": [
            { "id": 1101001, "description": "The mahotsav opens with a ceremonial deep prajwalan and evening aarati, bringing together families and elders in a peaceful devotional atmosphere.", "title": "Deep Prajwalan Aarati", "type": ProgramType.SPIRITUAL, "date": "2026-10-18", "from_time": "18:00", "to_time": "19:00", "photos": ["https://picsum.photos/seed/program-1101001-1/800/500", "https://picsum.photos/seed/program-1101001-2/800/500"], "locationCords": { "lat": 21.6482, "long": 81.4503 } },
            { "id": 1101002, "description": "Local artists perform folk songs, dance, and stage acts celebrating regional culture and community traditions.", "title": "Lok Sanskritik Sandhya", "type": ProgramType.CULTURAL, "date": "2026-10-19", "from_time": "19:30", "to_time": "21:30", "photos": ["https://picsum.photos/seed/program-1101002-1/800/500", "https://picsum.photos/seed/program-1101002-2/800/500"], "locationCords": { "lat": 21.6481, "long": 81.4504 } },
            { "id": 1101003, "description": "A large community meal is served to attendees and volunteers as a mark of gratitude and collective celebration.", "title": "Samuhik Bhandara", "type": ProgramType.BHANDARA, "date": "2026-10-20", "from_time": "12:00", "to_time": "14:30", "photos": ["https://picsum.photos/seed/program-1101003-1/800/500", "https://picsum.photos/seed/program-1101003-2/800/500"], "locationCords": { "lat": 21.6483, "long": 81.4502 } }
          ],
          "description": "Sharad Mahotsav is a three-day celebration featuring devotional programs, cultural performances, and community dining for families across the region."
        }
      ]
    }
    
  ];

  states: StateModel[] = [
    { id: 1,  name: 'Jammu and Kashmir',                             abbreviation: 'INJK', stateId: 1  },
    { id: 2,  name: 'Himachal Pradesh',                              abbreviation: 'INHP', stateId: 2  },
    { id: 3,  name: 'Punjab',                                        abbreviation: 'INPB', stateId: 3  },
    { id: 4,  name: 'Chandigarh',                                    abbreviation: 'INCH', stateId: 4  },
    { id: 5,  name: 'Uttaranchal',                                   abbreviation: 'INUT', stateId: 5  },
    { id: 6,  name: 'Haryana',                                       abbreviation: 'INHR', stateId: 6  },
    { id: 7,  name: 'Delhi',                                         abbreviation: 'INDL', stateId: 7  },
    { id: 8,  name: 'Rajasthan',                                     abbreviation: 'INRJ', stateId: 8  },
    { id: 9,  name: 'Uttar Pradesh',                                 abbreviation: 'INUP', stateId: 9  },
    { id: 10, name: 'Bihar',                                         abbreviation: 'INBR', stateId: 10 },
    { id: 11, name: 'Sikkim',                                        abbreviation: 'INSK', stateId: 11 },
    { id: 12, name: 'Arunachal Pradesh',                             abbreviation: 'INAR', stateId: 12 },
    { id: 13, name: 'Nagaland',                                      abbreviation: 'INNL', stateId: 13 },
    { id: 14, name: 'Manipur',                                       abbreviation: 'INMN', stateId: 14 },
    { id: 15, name: 'Mizoram',                                       abbreviation: 'INMZ', stateId: 15 },
    { id: 16, name: 'Tripura',                                       abbreviation: 'INTR', stateId: 16 },
    { id: 17, name: 'Meghalaya',                                     abbreviation: 'INML', stateId: 17 },
    { id: 18, name: 'Assam',                                         abbreviation: 'INAS', stateId: 18 },
    { id: 19, name: 'West Bengal',                                   abbreviation: 'INWB', stateId: 19 },
    { id: 20, name: 'Jharkhand',                                     abbreviation: 'INJH', stateId: 20 },
    { id: 21, name: 'Orissa',                                        abbreviation: 'INOR', stateId: 21 },
    { id: 22, name: 'Chhattisgarh',                                  abbreviation: 'INCT', stateId: 22 },
    { id: 23, name: 'Madhya Pradesh',                                abbreviation: 'INMP', stateId: 23 },
    { id: 24, name: 'Gujarat',                                       abbreviation: 'INGJ', stateId: 24 },
    { id: 25, name: 'Dādra and Nagar Haveli and Damān and Diu',      abbreviation: 'INDH', stateId: 26 },
    { id: 26, name: 'Maharashtra',                                   abbreviation: 'INMH', stateId: 27 },
    { id: 27, name: 'Karnataka',                                     abbreviation: 'INKA', stateId: 29 },
    { id: 28, name: 'Goa',                                           abbreviation: 'INGA', stateId: 30 },
    { id: 29, name: 'Lakshadweep',                                   abbreviation: 'INLD', stateId: 31 },
    { id: 30, name: 'Kerala',                                        abbreviation: 'INKL', stateId: 32 },
    { id: 31, name: 'Tamil Nadu',                                    abbreviation: 'INTN', stateId: 33 },
    { id: 32, name: 'Puducherry',                                    abbreviation: 'INPY', stateId: 34 },
    { id: 33, name: 'Andaman and Nicobar',                           abbreviation: 'INAN', stateId: 35 },
    { id: 34, name: 'Telangana',                                     abbreviation: 'INTG', stateId: 36 },
    { id: 35, name: 'Andhra Pradesh',                                abbreviation: 'INAP', stateId: 37 },
    { id: 36, name: 'Ladakh',                                        abbreviation: 'INLA', stateId: 38 },
  ];

  districts: { [stateId: number]: DistrictModel[] } = {
    1: [
      { id: 1,  name: 'Anantnag'       },
      { id: 2,  name: 'Bandipora'      },
      { id: 3,  name: 'Baramulla'      },
      { id: 4,  name: 'Budgam'         },
      { id: 5,  name: 'Doda'           },
      { id: 6,  name: 'Ganderbal'      },
      { id: 7,  name: 'Jammu'          },
      { id: 8,  name: 'Kathua'         },
      { id: 9,  name: 'Kishtwar'       },
      { id: 10, name: 'Kulgam'         },
      { id: 11, name: 'Kupwara'        },
      { id: 12, name: 'Poonch'         },
      { id: 13, name: 'Pulwama'        },
      { id: 14, name: 'Rajouri'        },
      { id: 15, name: 'Ramban'         },
      { id: 16, name: 'Reasi'          },
      { id: 17, name: 'Samba'          },
      { id: 18, name: 'Shopian'        },
      { id: 19, name: 'Srinagar'       },
      { id: 20, name: 'Udhampur'       },
    ],
    2: [
      { id: 1,  name: 'Bilaspur'         },
      { id: 2,  name: 'Chamba'           },
      { id: 3,  name: 'Hamirpur'         },
      { id: 4,  name: 'Kangra'           },
      { id: 5,  name: 'Kinnaur'          },
      { id: 6,  name: 'Kullu'            },
      { id: 7,  name: 'Lahaul and Spiti' },
      { id: 8,  name: 'Mandi'            },
      { id: 9,  name: 'Shimla'           },
      { id: 10, name: 'Sirmaur'          },
      { id: 11, name: 'Solan'            },
      { id: 12, name: 'Una'              },
    ],
    3: [
      { id: 1,  name: 'Amritsar'        },
      { id: 2,  name: 'Barnala'         },
      { id: 3,  name: 'Bathinda'        },
      { id: 4,  name: 'Faridkot'        },
      { id: 5,  name: 'Fatehgarh Sahib' },
      { id: 6,  name: 'Fazilka'         },
      { id: 7,  name: 'Ferozepur'       },
      { id: 8,  name: 'Gurdaspur'       },
      { id: 9,  name: 'Hoshiarpur'      },
      { id: 10, name: 'Jalandhar'       },
      { id: 11, name: 'Kapurthala'      },
      { id: 12, name: 'Ludhiana'        },
      { id: 13, name: 'Mansa'           },
      { id: 14, name: 'Moga'            },
      { id: 15, name: 'Mohali'          },
      { id: 16, name: 'Muktsar'         },
      { id: 17, name: 'Nawan Shahr'     },
      { id: 18, name: 'Pathankot'       },
      { id: 19, name: 'Patiala'         },
      { id: 20, name: 'Ropar'           },
      { id: 21, name: 'Sangrur'         },
      { id: 22, name: 'Tarn Taran'      },
    ],
    4: [
      { id: 1, name: 'Chandigarh' },
    ],
    5: [
      { id: 1,  name: 'Almora'           },
      { id: 2,  name: 'Bageshwar'        },
      { id: 3,  name: 'Chamoli'          },
      { id: 4,  name: 'Champawat'        },
      { id: 5,  name: 'Dehradun'         },
      { id: 6,  name: 'Haridwar'         },
      { id: 7,  name: 'Nainital'         },
      { id: 8,  name: 'Pauri Garhwal'    },
      { id: 9,  name: 'Pithoragarh'      },
      { id: 10, name: 'Rudraprayag'      },
      { id: 11, name: 'Tehri Garhwal'    },
      { id: 12, name: 'Udham Singh Nagar'},
      { id: 13, name: 'Uttarkashi'       },
    ],
    6: [
      { id: 1,  name: 'Ambala'         },
      { id: 2,  name: 'Bhiwani'        },
      { id: 3,  name: 'Charkhi Dadri'  },
      { id: 4,  name: 'Faridabad'      },
      { id: 5,  name: 'Fatehabad'      },
      { id: 6,  name: 'Gurugram'       },
      { id: 7,  name: 'Hisar'          },
      { id: 8,  name: 'Jhajjar'        },
      { id: 9,  name: 'Jind'           },
      { id: 10, name: 'Kaithal'        },
      { id: 11, name: 'Karnal'         },
      { id: 12, name: 'Kurukshetra'    },
      { id: 13, name: 'Mahendragarh'   },
      { id: 14, name: 'Nuh'            },
      { id: 15, name: 'Palwal'         },
      { id: 16, name: 'Panchkula'      },
      { id: 17, name: 'Panipat'        },
      { id: 18, name: 'Rewari'         },
      { id: 19, name: 'Rohtak'         },
      { id: 20, name: 'Sirsa'          },
      { id: 21, name: 'Sonipat'        },
      { id: 22, name: 'Yamunanagar'    },
    ],
    7: [
      { id: 1,  name: 'Central Delhi'    },
      { id: 2,  name: 'East Delhi'       },
      { id: 3,  name: 'New Delhi'        },
      { id: 4,  name: 'North Delhi'      },
      { id: 5,  name: 'North East Delhi' },
      { id: 6,  name: 'North West Delhi' },
      { id: 7,  name: 'Shahdara'         },
      { id: 8,  name: 'South Delhi'      },
      { id: 9,  name: 'South East Delhi' },
      { id: 10, name: 'South West Delhi' },
      { id: 11, name: 'West Delhi'       },
    ],
    8: [
      { id: 1,  name: 'Ajmer'           },
      { id: 2,  name: 'Alwar'           },
      { id: 3,  name: 'Banswara'        },
      { id: 4,  name: 'Baran'           },
      { id: 5,  name: 'Barmer'          },
      { id: 6,  name: 'Bharatpur'       },
      { id: 7,  name: 'Bhilwara'        },
      { id: 8,  name: 'Bikaner'         },
      { id: 9,  name: 'Bundi'           },
      { id: 10, name: 'Chittorgarh'     },
      { id: 11, name: 'Churu'           },
      { id: 12, name: 'Dausa'           },
      { id: 13, name: 'Dholpur'         },
      { id: 14, name: 'Dungarpur'       },
      { id: 15, name: 'Hanumangarh'     },
      { id: 16, name: 'Jaipur'          },
      { id: 17, name: 'Jaisalmer'       },
      { id: 18, name: 'Jalore'          },
      { id: 19, name: 'Jhalawar'        },
      { id: 20, name: 'Jhunjhunu'       },
      { id: 21, name: 'Jodhpur'         },
      { id: 22, name: 'Karauli'         },
      { id: 23, name: 'Kota'            },
      { id: 24, name: 'Nagaur'          },
      { id: 25, name: 'Pali'            },
      { id: 26, name: 'Pratapgarh'      },
      { id: 27, name: 'Rajsamand'       },
      { id: 28, name: 'Sawai Madhopur'  },
      { id: 29, name: 'Sikar'           },
      { id: 30, name: 'Sirohi'          },
      { id: 31, name: 'Sri Ganganagar'  },
      { id: 32, name: 'Tonk'            },
      { id: 33, name: 'Udaipur'         },
    ],
    9: [
      { id: 1,  name: 'Agra'                  },
      { id: 2,  name: 'Aligarh'               },
      { id: 3,  name: 'Prayagraj'             },
      { id: 4,  name: 'Ambedkar Nagar'        },
      { id: 5,  name: 'Amethi'                },
      { id: 6,  name: 'Amroha'                },
      { id: 7,  name: 'Auraiya'               },
      { id: 8,  name: 'Azamgarh'              },
      { id: 9,  name: 'Baghpat'               },
      { id: 10, name: 'Bahraich'              },
      { id: 11, name: 'Ballia'                },
      { id: 12, name: 'Balrampur'             },
      { id: 13, name: 'Banda'                 },
      { id: 14, name: 'Barabanki'             },
      { id: 15, name: 'Bareilly'              },
      { id: 16, name: 'Basti'                 },
      { id: 17, name: 'Bhadohi'               },
      { id: 18, name: 'Bijnor'                },
      { id: 19, name: 'Budaun'                },
      { id: 20, name: 'Bulandshahr'           },
      { id: 21, name: 'Chandauli'             },
      { id: 22, name: 'Chitrakoot'            },
      { id: 23, name: 'Deoria'                },
      { id: 24, name: 'Etah'                  },
      { id: 25, name: 'Etawah'                },
      { id: 26, name: 'Ayodhya'               },
      { id: 27, name: 'Farrukhabad'           },
      { id: 28, name: 'Fatehpur'              },
      { id: 29, name: 'Firozabad'             },
      { id: 30, name: 'Gautam Buddha Nagar'   },
      { id: 31, name: 'Ghaziabad'             },
      { id: 32, name: 'Ghazipur'              },
      { id: 33, name: 'Gonda'                 },
      { id: 34, name: 'Gorakhpur'             },
      { id: 35, name: 'Hamirpur'              },
      { id: 36, name: 'Hapur'                 },
      { id: 37, name: 'Hardoi'                },
      { id: 38, name: 'Hathras'               },
      { id: 39, name: 'Jalaun'                },
      { id: 40, name: 'Jaunpur'               },
      { id: 41, name: 'Jhansi'                },
      { id: 42, name: 'Kannauj'               },
      { id: 43, name: 'Kanpur Dehat'          },
      { id: 44, name: 'Kanpur Nagar'          },
      { id: 45, name: 'Kasganj'               },
      { id: 46, name: 'Kaushambi'             },
      { id: 47, name: 'Kushinagar'            },
      { id: 48, name: 'Lakhimpur Kheri'       },
      { id: 49, name: 'Lalitpur'              },
      { id: 50, name: 'Lucknow'               },
      { id: 51, name: 'Maharajganj'           },
      { id: 52, name: 'Mahoba'                },
      { id: 53, name: 'Mainpuri'              },
      { id: 54, name: 'Mathura'               },
      { id: 55, name: 'Mau'                   },
      { id: 56, name: 'Meerut'                },
      { id: 57, name: 'Mirzapur'              },
      { id: 58, name: 'Moradabad'             },
      { id: 59, name: 'Muzaffarnagar'         },
      { id: 60, name: 'Pilibhit'              },
      { id: 61, name: 'Pratapgarh'            },
      { id: 62, name: 'Rae Bareli'            },
      { id: 63, name: 'Rampur'                },
      { id: 64, name: 'Saharanpur'            },
      { id: 65, name: 'Sambhal'               },
      { id: 66, name: 'Sant Kabir Nagar'      },
      { id: 67, name: 'Shahjahanpur'          },
      { id: 68, name: 'Shamli'                },
      { id: 69, name: 'Shravasti'             },
      { id: 70, name: 'Siddharthnagar'        },
      { id: 71, name: 'Sitapur'               },
      { id: 72, name: 'Sonbhadra'             },
      { id: 73, name: 'Sultanpur'             },
      { id: 74, name: 'Unnao'                 },
      { id: 75, name: 'Varanasi'              },
    ],
    10: [
      { id: 1,  name: 'Araria'          },
      { id: 2,  name: 'Arwal'           },
      { id: 3,  name: 'Aurangabad'      },
      { id: 4,  name: 'Banka'           },
      { id: 5,  name: 'Begusarai'       },
      { id: 6,  name: 'Bhagalpur'       },
      { id: 7,  name: 'Bhojpur'         },
      { id: 8,  name: 'Buxar'           },
      { id: 9,  name: 'Darbhanga'       },
      { id: 10, name: 'East Champaran'  },
      { id: 11, name: 'Gaya'            },
      { id: 12, name: 'Gopalganj'       },
      { id: 13, name: 'Jamui'           },
      { id: 14, name: 'Jehanabad'       },
      { id: 15, name: 'Kaimur'          },
      { id: 16, name: 'Katihar'         },
      { id: 17, name: 'Khagaria'        },
      { id: 18, name: 'Kishanganj'      },
      { id: 19, name: 'Lakhisarai'      },
      { id: 20, name: 'Madhepura'       },
      { id: 21, name: 'Madhubani'       },
      { id: 22, name: 'Munger'          },
      { id: 23, name: 'Muzaffarpur'     },
      { id: 24, name: 'Nalanda'         },
      { id: 25, name: 'Nawada'          },
      { id: 26, name: 'Patna'           },
      { id: 27, name: 'Purnia'          },
      { id: 28, name: 'Rohtas'          },
      { id: 29, name: 'Saharsa'         },
      { id: 30, name: 'Samastipur'      },
      { id: 31, name: 'Saran'           },
      { id: 32, name: 'Sheikhpura'      },
      { id: 33, name: 'Sheohar'         },
      { id: 34, name: 'Sitamarhi'       },
      { id: 35, name: 'Siwan'           },
      { id: 36, name: 'Supaul'          },
      { id: 37, name: 'Vaishali'        },
      { id: 38, name: 'West Champaran'  },
    ],
    11: [
      { id: 1, name: 'East Sikkim'  },
      { id: 2, name: 'North Sikkim' },
      { id: 3, name: 'South Sikkim' },
      { id: 4, name: 'West Sikkim'  },
    ],
    12: [
      { id: 1,  name: 'Anjaw'                },
      { id: 2,  name: 'Changlang'            },
      { id: 3,  name: 'Dibang Valley'        },
      { id: 4,  name: 'East Kameng'          },
      { id: 5,  name: 'East Siang'           },
      { id: 6,  name: 'Kamle'                },
      { id: 7,  name: 'Kra Daadi'            },
      { id: 8,  name: 'Kurung Kumey'         },
      { id: 9,  name: 'Lepa Rada'            },
      { id: 10, name: 'Lohit'                },
      { id: 11, name: 'Longding'             },
      { id: 12, name: 'Lower Dibang Valley'  },
      { id: 13, name: 'Lower Siang'          },
      { id: 14, name: 'Lower Subansiri'      },
      { id: 15, name: 'Namsai'               },
      { id: 16, name: 'Pakke-Kessang'        },
      { id: 17, name: 'Papum Pare'           },
      { id: 18, name: 'Shi Yomi'             },
      { id: 19, name: 'Siang'                },
      { id: 20, name: 'Tawang'               },
      { id: 21, name: 'Tirap'                },
      { id: 22, name: 'Upper Siang'          },
      { id: 23, name: 'Upper Subansiri'      },
      { id: 24, name: 'West Kameng'          },
      { id: 25, name: 'West Siang'           },
    ],
    13: [
      { id: 1,  name: 'Chumoukedima' },
      { id: 2,  name: 'Dimapur'      },
      { id: 3,  name: 'Kiphire'      },
      { id: 4,  name: 'Kohima'       },
      { id: 5,  name: 'Longleng'     },
      { id: 6,  name: 'Mokokchung'   },
      { id: 7,  name: 'Mon'          },
      { id: 8,  name: 'Niuland'      },
      { id: 9,  name: 'Noklak'       },
      { id: 10, name: 'Peren'        },
      { id: 11, name: 'Phek'         },
      { id: 12, name: 'Shamator'     },
      { id: 13, name: 'Tseminyü'     },
      { id: 14, name: 'Tuensang'     },
      { id: 15, name: 'Wokha'        },
      { id: 16, name: 'Zunheboto'    },
    ],
    14: [
      { id: 1,  name: 'Bishnupur'    },
      { id: 2,  name: 'Chandel'      },
      { id: 3,  name: 'Churachandpur'},
      { id: 4,  name: 'Imphal East'  },
      { id: 5,  name: 'Imphal West'  },
      { id: 6,  name: 'Jiribam'      },
      { id: 7,  name: 'Kakching'     },
      { id: 8,  name: 'Kamjong'      },
      { id: 9,  name: 'Kangpokpi'    },
      { id: 10, name: 'Noney'        },
      { id: 11, name: 'Pherzawl'     },
      { id: 12, name: 'Senapati'     },
      { id: 13, name: 'Tamenglong'   },
      { id: 14, name: 'Tengnoupal'   },
      { id: 15, name: 'Thoubal'      },
      { id: 16, name: 'Ukhrul'       },
    ],
    15: [
      { id: 1,  name: 'Aizawl'     },
      { id: 2,  name: 'Champhai'   },
      { id: 3,  name: 'Hnahthial'  },
      { id: 4,  name: 'Khawzawl'   },
      { id: 5,  name: 'Kolasib'    },
      { id: 6,  name: 'Lawngtlai'  },
      { id: 7,  name: 'Lunglei'    },
      { id: 8,  name: 'Mamit'      },
      { id: 9,  name: 'Saitual'    },
      { id: 10, name: 'Serchhip'   },
    ],
    16: [
      { id: 1, name: 'Dhalai'        },
      { id: 2, name: 'Gomati'        },
      { id: 3, name: 'Khowai'        },
      { id: 4, name: 'North Tripura' },
      { id: 5, name: 'Sepahijala'    },
      { id: 6, name: 'South Tripura' },
      { id: 7, name: 'Unakoti'       },
      { id: 8, name: 'West Tripura'  },
    ],
    17: [
      { id: 1,  name: 'East Garo Hills'          },
      { id: 2,  name: 'East Jaintia Hills'        },
      { id: 3,  name: 'East Khasi Hills'          },
      { id: 4,  name: 'Eastern West Khasi Hills'  },
      { id: 5,  name: 'North Garo Hills'          },
      { id: 6,  name: 'Ri Bhoi'                   },
      { id: 7,  name: 'South Garo Hills'          },
      { id: 8,  name: 'South West Garo Hills'     },
      { id: 9,  name: 'South West Khasi Hills'    },
      { id: 10, name: 'West Garo Hills'           },
      { id: 11, name: 'West Jaintia Hills'        },
      { id: 12, name: 'West Khasi Hills'          },
    ],
    18: [
      { id: 1,  name: 'Bajali'                    },
      { id: 2,  name: 'Baksa'                     },
      { id: 3,  name: 'Barpeta'                   },
      { id: 4,  name: 'Biswanath'                 },
      { id: 5,  name: 'Bongaigaon'                },
      { id: 6,  name: 'Cachar'                    },
      { id: 7,  name: 'Charaideo'                 },
      { id: 8,  name: 'Chirang'                   },
      { id: 9,  name: 'Darrang'                   },
      { id: 10, name: 'Dhemaji'                   },
      { id: 11, name: 'Dhubri'                    },
      { id: 12, name: 'Dibrugarh'                 },
      { id: 13, name: 'Dima Hasao'                },
      { id: 14, name: 'Goalpara'                  },
      { id: 15, name: 'Golaghat'                  },
      { id: 16, name: 'Hailakandi'                },
      { id: 17, name: 'Hojai'                     },
      { id: 18, name: 'Jorhat'                    },
      { id: 19, name: 'Kamrup'                    },
      { id: 20, name: 'Kamrup Metropolitan'       },
      { id: 21, name: 'Karbi Anglong'             },
      { id: 22, name: 'Karimganj'                 },
      { id: 23, name: 'Kokrajhar'                 },
      { id: 24, name: 'Lakhimpur'                 },
      { id: 25, name: 'Majuli'                    },
      { id: 26, name: 'Morigaon'                  },
      { id: 27, name: 'Nagaon'                    },
      { id: 28, name: 'Nalbari'                   },
      { id: 29, name: 'Sivasagar'                 },
      { id: 30, name: 'Sonitpur'                  },
      { id: 31, name: 'South Salmara-Mankachar'   },
      { id: 32, name: 'Tinsukia'                  },
      { id: 33, name: 'Udalguri'                  },
      { id: 34, name: 'West Karbi Anglong'        },
    ],
    19: [
      { id: 1,  name: 'Alipurduar'          },
      { id: 2,  name: 'Bankura'             },
      { id: 3,  name: 'Birbhum'             },
      { id: 4,  name: 'Cooch Behar'         },
      { id: 5,  name: 'Dakshin Dinajpur'    },
      { id: 6,  name: 'Darjeeling'          },
      { id: 7,  name: 'Hooghly'             },
      { id: 8,  name: 'Howrah'              },
      { id: 9,  name: 'Jalpaiguri'          },
      { id: 10, name: 'Jhargram'            },
      { id: 11, name: 'Kalimpong'           },
      { id: 12, name: 'Kolkata'             },
      { id: 13, name: 'Malda'               },
      { id: 14, name: 'Murshidabad'         },
      { id: 15, name: 'Nadia'               },
      { id: 16, name: 'North 24 Parganas'   },
      { id: 17, name: 'Paschim Bardhaman'   },
      { id: 18, name: 'Paschim Medinipur'   },
      { id: 19, name: 'Purba Bardhaman'     },
      { id: 20, name: 'Purba Medinipur'     },
      { id: 21, name: 'Purulia'             },
      { id: 22, name: 'South 24 Parganas'   },
      { id: 23, name: 'Uttar Dinajpur'      },
    ],
    20: [
      { id: 1,  name: 'Bokaro'                  },
      { id: 2,  name: 'Chatra'                  },
      { id: 3,  name: 'Deoghar'                 },
      { id: 4,  name: 'Dhanbad'                 },
      { id: 5,  name: 'Dumka'                   },
      { id: 6,  name: 'East Singhbhum'          },
      { id: 7,  name: 'Garhwa'                  },
      { id: 8,  name: 'Giridih'                 },
      { id: 9,  name: 'Godda'                   },
      { id: 10, name: 'Gumla'                   },
      { id: 11, name: 'Hazaribagh'              },
      { id: 12, name: 'Jamtara'                 },
      { id: 13, name: 'Khunti'                  },
      { id: 14, name: 'Koderma'                 },
      { id: 15, name: 'Latehar'                 },
      { id: 16, name: 'Lohardaga'               },
      { id: 17, name: 'Pakur'                   },
      { id: 18, name: 'Palamu'                  },
      { id: 19, name: 'Ramgarh'                 },
      { id: 20, name: 'Ranchi'                  },
      { id: 21, name: 'Sahebganj'               },
      { id: 22, name: 'Seraikela Kharsawan'     },
      { id: 23, name: 'Simdega'                 },
      { id: 24, name: 'West Singhbhum'          },
    ],
    21: [
      { id: 1,  name: 'Angul'          },
      { id: 2,  name: 'Balangir'       },
      { id: 3,  name: 'Balasore'       },
      { id: 4,  name: 'Bargarh'        },
      { id: 5,  name: 'Bhadrak'        },
      { id: 6,  name: 'Boudh'          },
      { id: 7,  name: 'Cuttack'        },
      { id: 8,  name: 'Deogarh'        },
      { id: 9,  name: 'Dhenkanal'      },
      { id: 10, name: 'Gajapati'       },
      { id: 11, name: 'Ganjam'         },
      { id: 12, name: 'Jagatsinghpur'  },
      { id: 13, name: 'Jajpur'         },
      { id: 14, name: 'Jharsuguda'     },
      { id: 15, name: 'Kalahandi'      },
      { id: 16, name: 'Kandhamal'      },
      { id: 17, name: 'Kendrapara'     },
      { id: 18, name: 'Kendujhar'      },
      { id: 19, name: 'Khordha'        },
      { id: 20, name: 'Koraput'        },
      { id: 21, name: 'Malkangiri'     },
      { id: 22, name: 'Mayurbhanj'     },
      { id: 23, name: 'Nabarangpur'    },
      { id: 24, name: 'Nayagarh'       },
      { id: 25, name: 'Nuapada'        },
      { id: 26, name: 'Puri'           },
      { id: 27, name: 'Rayagada'       },
      { id: 28, name: 'Sambalpur'      },
      { id: 29, name: 'Subarnapur'     },
      { id: 30, name: 'Sundergarh'     },
    ],
    22: [
      { id: 1,  name: 'Balod'         },
      { id: 2,  name: 'Baloda Bazar'  },
      { id: 3,  name: 'Balrampur'     },
      { id: 4,  name: 'Bametara'      },
      { id: 5,  name: 'Bijapur'       },
      { id: 6,  name: 'Bilaspur'      },
      { id: 7,  name: 'Dantewada'     },
      { id: 8,  name: 'Dhamtari'      },
      { id: 9,  name: 'Durg'          },
      { id: 10, name: 'Gariaband'     },
      { id: 11, name: 'Janjgir-Champa'},
      { id: 12, name: 'Jashpur'       },
      { id: 13, name: 'Kanker'        },
      { id: 14, name: 'Kawardha'      },
      { id: 15, name: 'Korba'         },
      { id: 16, name: 'Koriya'        },
      { id: 17, name: 'Mahasamund'    },
      { id: 18, name: 'Mungeli'       },
      { id: 19, name: 'Narayanpur'    },
      { id: 20, name: 'Raigarh'       },
      { id: 21, name: 'Raipur'        },
      { id: 22, name: 'Rajnandgaon'   },
      { id: 23, name: 'Sukma'         },
      { id: 24, name: 'Surajpur'      },
      { id: 25, name: 'Surguja'       },
    ],
    23: [
      { id: 1,  name: 'Agar Malwa'    },
      { id: 2,  name: 'Alirajpur'     },
      { id: 3,  name: 'Anuppur'       },
      { id: 4,  name: 'Ashoknagar'    },
      { id: 5,  name: 'Balaghat'      },
      { id: 6,  name: 'Barwani'       },
      { id: 7,  name: 'Betul'         },
      { id: 8,  name: 'Bhind'         },
      { id: 9,  name: 'Bhopal'        },
      { id: 10, name: 'Burhanpur'     },
      { id: 11, name: 'Chhatarpur'    },
      { id: 12, name: 'Chhindwara'    },
      { id: 13, name: 'Damoh'         },
      { id: 14, name: 'Datia'         },
      { id: 15, name: 'Dewas'         },
      { id: 16, name: 'Dhar'          },
      { id: 17, name: 'Dindori'       },
      { id: 18, name: 'Guna'          },
      { id: 19, name: 'Gwalior'       },
      { id: 20, name: 'Harda'         },
      { id: 21, name: 'Narmadapuram'  },
      { id: 22, name: 'Indore'        },
      { id: 23, name: 'Jabalpur'      },
      { id: 24, name: 'Jhabua'        },
      { id: 25, name: 'Katni'         },
      { id: 26, name: 'Khandwa'       },
      { id: 27, name: 'Khargone'      },
      { id: 28, name: 'Mandla'        },
      { id: 29, name: 'Mandsaur'      },
      { id: 30, name: 'Morena'        },
      { id: 31, name: 'Narsinghpur'   },
      { id: 32, name: 'Neemuch'       },
      { id: 33, name: 'Niwari'        },
      { id: 34, name: 'Panna'         },
      { id: 35, name: 'Raisen'        },
      { id: 36, name: 'Rajgarh'       },
      { id: 37, name: 'Ratlam'        },
      { id: 38, name: 'Rewa'          },
      { id: 39, name: 'Sagar'         },
      { id: 40, name: 'Satna'         },
      { id: 41, name: 'Sehore'        },
      { id: 42, name: 'Seoni'         },
      { id: 43, name: 'Shahdol'       },
      { id: 44, name: 'Shajapur'      },
      { id: 45, name: 'Sheopur'       },
      { id: 46, name: 'Shivpuri'      },
      { id: 47, name: 'Sidhi'         },
      { id: 48, name: 'Singrauli'     },
      { id: 49, name: 'Tikamgarh'     },
      { id: 50, name: 'Ujjain'        },
      { id: 51, name: 'Umaria'        },
      { id: 52, name: 'Vidisha'       },
    ],
    24: [
      { id: 1,  name: 'Ahmedabad'          },
      { id: 2,  name: 'Amreli'             },
      { id: 3,  name: 'Anand'              },
      { id: 4,  name: 'Aravalli'           },
      { id: 5,  name: 'Banaskantha'        },
      { id: 6,  name: 'Bharuch'            },
      { id: 7,  name: 'Bhavnagar'          },
      { id: 8,  name: 'Botad'              },
      { id: 9,  name: 'Chhota Udaipur'     },
      { id: 10, name: 'Dahod'              },
      { id: 11, name: 'Dang'               },
      { id: 12, name: 'Devbhoomi Dwarka'   },
      { id: 13, name: 'Gandhinagar'        },
      { id: 14, name: 'Gir Somnath'        },
      { id: 15, name: 'Jamnagar'           },
      { id: 16, name: 'Junagadh'           },
      { id: 17, name: 'Kheda'              },
      { id: 18, name: 'Kutch'              },
      { id: 19, name: 'Mahisagar'          },
      { id: 20, name: 'Mehsana'            },
      { id: 21, name: 'Morbi'              },
      { id: 22, name: 'Narmada'            },
      { id: 23, name: 'Navsari'            },
      { id: 24, name: 'Panchmahal'         },
      { id: 25, name: 'Patan'              },
      { id: 26, name: 'Porbandar'          },
      { id: 27, name: 'Rajkot'             },
      { id: 28, name: 'Sabarkantha'        },
      { id: 29, name: 'Surat'              },
      { id: 30, name: 'Surendranagar'      },
      { id: 31, name: 'Tapi'               },
      { id: 32, name: 'Vadodara'           },
      { id: 33, name: 'Valsad'             },
    ],
    25: [
      { id: 1, name: 'Dadra and Nagar Haveli' },
      { id: 2, name: 'Daman'                  },
      { id: 3, name: 'Diu'                    },
    ],
    26: [
      { id: 1,  name: 'Ahmednagar'      },
      { id: 2,  name: 'Akola'           },
      { id: 3,  name: 'Amravati'        },
      { id: 4,  name: 'Aurangabad'      },
      { id: 5,  name: 'Beed'            },
      { id: 6,  name: 'Bhandara'        },
      { id: 7,  name: 'Buldhana'        },
      { id: 8,  name: 'Chandrapur'      },
      { id: 9,  name: 'Dhule'           },
      { id: 10, name: 'Gadchiroli'      },
      { id: 11, name: 'Gondia'          },
      { id: 12, name: 'Hingoli'         },
      { id: 13, name: 'Jalgaon'         },
      { id: 14, name: 'Jalna'           },
      { id: 15, name: 'Kolhapur'        },
      { id: 16, name: 'Latur'           },
      { id: 17, name: 'Mumbai City'     },
      { id: 18, name: 'Mumbai Suburban' },
      { id: 19, name: 'Nagpur'          },
      { id: 20, name: 'Nanded'          },
      { id: 21, name: 'Nandurbar'       },
      { id: 22, name: 'Nashik'          },
      { id: 23, name: 'Osmanabad'       },
      { id: 24, name: 'Palghar'         },
      { id: 25, name: 'Parbhani'        },
      { id: 26, name: 'Pune'            },
      { id: 27, name: 'Raigad'          },
      { id: 28, name: 'Ratnagiri'       },
      { id: 29, name: 'Sangli'          },
      { id: 30, name: 'Satara'          },
      { id: 31, name: 'Sindhudurg'      },
      { id: 32, name: 'Solapur'         },
      { id: 33, name: 'Thane'           },
      { id: 34, name: 'Wardha'          },
      { id: 35, name: 'Washim'          },
      { id: 36, name: 'Yavatmal'        },
    ],
    27: [
      { id: 1,  name: 'Bagalkot'         },
      { id: 2,  name: 'Ballari'          },
      { id: 3,  name: 'Belagavi'         },
      { id: 4,  name: 'Bengaluru Rural'  },
      { id: 5,  name: 'Bengaluru Urban'  },
      { id: 6,  name: 'Bidar'            },
      { id: 7,  name: 'Chamarajanagar'   },
      { id: 8,  name: 'Chikkaballapur'   },
      { id: 9,  name: 'Chikkamagaluru'   },
      { id: 10, name: 'Chitradurga'      },
      { id: 11, name: 'Dakshina Kannada' },
      { id: 12, name: 'Davanagere'       },
      { id: 13, name: 'Dharwad'          },
      { id: 14, name: 'Gadag'            },
      { id: 15, name: 'Hassan'           },
      { id: 16, name: 'Haveri'           },
      { id: 17, name: 'Kalaburagi'       },
      { id: 18, name: 'Kodagu'           },
      { id: 19, name: 'Kolar'            },
      { id: 20, name: 'Koppal'           },
      { id: 21, name: 'Mandya'           },
      { id: 22, name: 'Mysuru'           },
      { id: 23, name: 'Raichur'          },
      { id: 24, name: 'Ramanagara'       },
      { id: 25, name: 'Shivamogga'       },
      { id: 26, name: 'Tumakuru'         },
      { id: 27, name: 'Udupi'            },
      { id: 28, name: 'Uttara Kannada'   },
      { id: 29, name: 'Vijayapura'       },
      { id: 30, name: 'Yadgir'           },
    ],
    28: [
      { id: 1, name: 'North Goa' },
      { id: 2, name: 'South Goa' },
    ],
    29: [
      { id: 1,  name: 'Agatti'    },
      { id: 2,  name: 'Amini'     },
      { id: 3,  name: 'Andrott'   },
      { id: 4,  name: 'Bitra'     },
      { id: 5,  name: 'Chetlat'   },
      { id: 6,  name: 'Kadmat'    },
      { id: 7,  name: 'Kalpeni'   },
      { id: 8,  name: 'Kavaratti' },
      { id: 9,  name: 'Kiltan'    },
      { id: 10, name: 'Minicoy'   },
    ],
    30: [
      { id: 1,  name: 'Alappuzha'        },
      { id: 2,  name: 'Ernakulam'        },
      { id: 3,  name: 'Idukki'           },
      { id: 4,  name: 'Kannur'           },
      { id: 5,  name: 'Kasaragod'        },
      { id: 6,  name: 'Kollam'           },
      { id: 7,  name: 'Kottayam'         },
      { id: 8,  name: 'Kozhikode'        },
      { id: 9,  name: 'Malappuram'       },
      { id: 10, name: 'Palakkad'         },
      { id: 11, name: 'Pathanamthitta'   },
      { id: 12, name: 'Thiruvananthapuram'},
      { id: 13, name: 'Thrissur'         },
      { id: 14, name: 'Wayanad'          },
    ],
    31: [
      { id: 1,  name: 'Ariyalur'        },
      { id: 2,  name: 'Chengalpattu'    },
      { id: 3,  name: 'Chennai'         },
      { id: 4,  name: 'Coimbatore'      },
      { id: 5,  name: 'Cuddalore'       },
      { id: 6,  name: 'Dharmapuri'      },
      { id: 7,  name: 'Dindigul'        },
      { id: 8,  name: 'Erode'           },
      { id: 9,  name: 'Kallakurichi'    },
      { id: 10, name: 'Kancheepuram'    },
      { id: 11, name: 'Kanyakumari'     },
      { id: 12, name: 'Karur'           },
      { id: 13, name: 'Krishnagiri'     },
      { id: 14, name: 'Madurai'         },
      { id: 15, name: 'Mayiladuthurai'  },
      { id: 16, name: 'Nagapattinam'    },
      { id: 17, name: 'Namakkal'        },
      { id: 18, name: 'Nilgiris'        },
      { id: 19, name: 'Perambalur'      },
      { id: 20, name: 'Pudukkottai'     },
      { id: 21, name: 'Ramanathapuram'  },
      { id: 22, name: 'Ranipet'         },
      { id: 23, name: 'Salem'           },
      { id: 24, name: 'Sivaganga'       },
      { id: 25, name: 'Tenkasi'         },
      { id: 26, name: 'Thanjavur'       },
      { id: 27, name: 'Theni'           },
      { id: 28, name: 'Thoothukudi'     },
      { id: 29, name: 'Tiruchirappalli' },
      { id: 30, name: 'Tirunelveli'     },
      { id: 31, name: 'Tirupathur'      },
      { id: 32, name: 'Tiruppur'        },
      { id: 33, name: 'Tiruvallur'      },
      { id: 34, name: 'Tiruvannamalai'  },
      { id: 35, name: 'Tiruvarur'       },
      { id: 36, name: 'Vellore'         },
      { id: 37, name: 'Viluppuram'      },
      { id: 38, name: 'Virudhunagar'    },
    ],
    32: [
      { id: 1, name: 'Karaikal'   },
      { id: 2, name: 'Mahe'       },
      { id: 3, name: 'Puducherry' },
      { id: 4, name: 'Yanam'      },
    ],
    33: [
      { id: 1, name: 'Nicobar'                  },
      { id: 2, name: 'North and Middle Andaman'  },
      { id: 3, name: 'South Andaman'             },
    ],
    34: [
      { id: 1,  name: 'Adilabad'                  },
      { id: 2,  name: 'Bhadradri Kothagudem'       },
      { id: 3,  name: 'Hanumakonda'                },
      { id: 4,  name: 'Hyderabad'                  },
      { id: 5,  name: 'Jagtial'                    },
      { id: 6,  name: 'Jangaon'                    },
      { id: 7,  name: 'Jayashankar Bhupalpally'    },
      { id: 8,  name: 'Jogulamba Gadwal'           },
      { id: 9,  name: 'Kamareddy'                  },
      { id: 10, name: 'Karimnagar'                 },
      { id: 11, name: 'Khammam'                    },
      { id: 12, name: 'Kumuram Bheem'              },
      { id: 13, name: 'Mahabubabad'                },
      { id: 14, name: 'Mahabubnagar'               },
      { id: 15, name: 'Mancherial'                 },
      { id: 16, name: 'Medak'                      },
      { id: 17, name: 'Medchal-Malkajgiri'         },
      { id: 18, name: 'Mulugu'                     },
      { id: 19, name: 'Nagarkurnool'               },
      { id: 20, name: 'Nalgonda'                   },
      { id: 21, name: 'Narayanpet'                 },
      { id: 22, name: 'Nirmal'                     },
      { id: 23, name: 'Nizamabad'                  },
      { id: 24, name: 'Peddapalli'                 },
      { id: 25, name: 'Rajanna Sircilla'           },
      { id: 26, name: 'Ranga Reddy'                },
      { id: 27, name: 'Sangareddy'                 },
      { id: 28, name: 'Siddipet'                   },
      { id: 29, name: 'Suryapet'                   },
      { id: 30, name: 'Vikarabad'                  },
      { id: 31, name: 'Wanaparthy'                 },
      { id: 32, name: 'Warangal Rural'             },
      { id: 33, name: 'Warangal Urban'             },
      { id: 34, name: 'Yadadri Bhuvanagiri'        },
    ],
    35: [
      { id: 1,  name: 'Alluri Sitharama Raju'           },
      { id: 2,  name: 'Anakapalli'                       },
      { id: 3,  name: 'Ananthapuramu'                    },
      { id: 4,  name: 'Annamayya'                        },
      { id: 5,  name: 'Bapatla'                          },
      { id: 6,  name: 'Chittoor'                         },
      { id: 7,  name: 'Dr. B.R. Ambedkar Konaseema'      },
      { id: 8,  name: 'East Godavari'                    },
      { id: 9,  name: 'Eluru'                            },
      { id: 10, name: 'Guntur'                           },
      { id: 11, name: 'Kakinada'                         },
      { id: 12, name: 'Krishna'                          },
      { id: 13, name: 'Kurnool'                          },
      { id: 14, name: 'Nandyal'                          },
      { id: 15, name: 'NTR'                              },
      { id: 16, name: 'Palnadu'                          },
      { id: 17, name: 'Parvathipuram Manyam'             },
      { id: 18, name: 'Prakasam'                         },
      { id: 19, name: 'Sri Potti Sriramulu Nellore'      },
      { id: 20, name: 'Sri Sathya Sai'                   },
      { id: 21, name: 'Srikakulam'                       },
      { id: 22, name: 'Tirupati'                         },
      { id: 23, name: 'Visakhapatnam'                    },
      { id: 24, name: 'Vizianagaram'                     },
      { id: 25, name: 'West Godavari'                    },
      { id: 26, name: 'YSR Kadapa'                       },
    ],
    36: [
      { id: 1, name: 'Kargil' },
      { id: 2, name: 'Leh'    },
    ],
  };

  groupSearchTerm = signal<string>('');
  groupSelectedDistance = signal<number>(1); // Default distance in kilometers

  getGroupsEventsPrograms(): Observable<GroupDetailsModel[]> {
    // return this.http.get<any>(this.apiUrl);
    return new Observable(observer => {
      observer.next(this.samitiGroups);
      observer.complete();
    });
  }

  getStates(): Observable<StateModel[]> {
    // return this.http.get<StateModel[]>('api/states');
    return new Observable(observer => {
      observer.next(this.states);
      observer.complete();
    });
  }

  getDistricts(stateId: number): Observable<DistrictModel[]> {
    // return this.http.get<DistrictModel[]>(`api/districts/${stateId}`);
    return new Observable(observer => {
      observer.next(this.districts[stateId] ?? []);
      observer.complete();
    });
  }

  getAreas(districtId: number): Observable<{ id: number; name: string }[]> {
    return this.http.get<{ id: number; name: string }[]>(`api/areas/${districtId}`);
  }

  createSamiti(payload: CreateSamitiModel): Observable<{ id: number; message: string }> {
    return this.http.post<{ id: number; message: string }>(`${this.baseUrl}/groups`, payload);
  }
}
